### ISSUE TITLE
docker restore failed

### ISSUE THREAD

**Issue by yogeshVU** [xemul/criu#293] opened 2017-03-14 21:21 UTC
Created two checkpoints: check1 and check2 in that order. But when I try to restore from check1 I get following error
` (cr-restore.c:1387): 18474 killed by signal 9: Killed
`
`
(00.637674) Error (cr-restore.c:2226): Restoring FAILED.
`
Full Error log: https://gist.github.com/yogeshVU/5e895518e33c7c9d1023b1a6f8135ee0

How can I resolve this issue and have safe C/R

Docker Version:
Docker version 17.03.0-ce, build 3a232c8

CRIU Version: 2.2

**Comment by avagin** [comment] 2017-03-14 22:42
```
[avagin@laptop criu]$ curl https://gist.githubusercontent.com/yogeshVU/5e895518e33c7c9d1023b1a6f8135ee0/raw/0679974347b68cc25281eea7f427b376c82852a7/restore.log | grep Error
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0(00.580418)  28658: Error (files-reg.c:1524): Can't open file var/lib/phoronix-test-suite/installed-tests/pts/build-linux-kernel-1.7.0/linux-4.9/drivers/pcmcia/rsrc_nonstatic.o on restore: No such file or directory
(00.580426)  28658: Error (files-reg.c:1466): Can't open file var/lib/phoronix-test-suite/installed-tests/pts/build-linux-kernel-1.7.0/linux-4.9/drivers/pcmcia/rsrc_nonstatic.o: No such file or directory
(00.580675)  28675: Error (files-reg.c:1524): Can't open file var/lib/phoronix-test-suite/installed-tests/pts/build-linux-kernel-1.7.0/linux-4.9/drivers/pci/pcie/aspm.o on restore: No such file or directory
(00.580682)  28675: Error (files-reg.c:1466): Can't open file var/lib/phoronix-test-suite/installed-tests/pts/build-linux-kernel-1.7.0/linux-4.9/drivers/pci/pcie/aspm.o: No such file or directory
(00.580702)  28670: Error (files-reg.c:1524): Can't open file var/lib/phoronix-test-suite/installed-tests/pts/build-linux-kernel-1.7.0/linux-4.9/drivers/pci/hotplug/pci_hotplug_core.o on restore: No such file or directory
(00.580707)  28670: Error (files-reg.c:1466): Can't open file var/lib/phoronix-test-suite/installed-tests/pts/build-linux-kernel-1.7.0/linux-4.9/drivers/pci/hotplug/pci_hotplug_core.o: No such file or directory
(00.581696)  28696: Error (files-reg.c:1524): Can't open file var/lib/phoronix-test-suite/installed-tests/pts/build-linux-kernel-1.7.0/linux-4.9/drivers/gpu/drm/i915/intel_dsi_dcs_backlight.o on restore: No such file or directory
(00.581701)  28696: Error (files-reg.c:1466): Can't open file var/lib/phoronix-test-suite/installed-tests/pts/build-linux-kernel-1.7.0/linux-4.9/drivers/gpu/drm/i915/intel_dsi_dcs_backlight.o: No such file or directory
(00.581950)  28654: Error (cr-restore.c:1384): 28658 exited, status=1
100  747k (00.582789)  28673: Error (cr-restore.c:1384): 28675 exited, status=1
 100  747k    0     0  1241k      0 --:--:-- --:--:-- --:--:-- 1241k
(00.582867)  28689: Error (files-reg.c:1524): Can't open file var/lib/phoronix-test-suite/installed-tests/pts/build-linux-kernel-1.7.0/linux-4.9/drivers/gpu/drm/i915/intel_dsi.o on restore: No such file or directory
(00.582872)  28689: Error (files-reg.c:1466): Can't open file var/lib/phoronix-test-suite/installed-tests/pts/build-linux-kernel-1.7.0/linux-4.9/drivers/gpu/drm/i915/intel_dsi.o: No such file or directory
(00.583137)  28667: Error (cr-restore.c:1384): 28670 exited, status=1
(00.583156)  28694: Error (cr-restore.c:1384): 28696 exited, status=1
(00.583398)  28683: Error (files-reg.c:1524): Can't open file var/lib/phoronix-test-suite/installed-tests/pts/build-linux-kernel-1.7.0/linux-4.9/drivers/gpu/drm/i915/intel_dp.o on restore: No such file or directory
(00.583403)  28683: Error (files-reg.c:1466): Can't open file var/lib/phoronix-test-suite/installed-tests/pts/build-linux-kernel-1.7.0/linux-4.9/drivers/gpu/drm/i915/intel_dp.o: No such file or directory
(00.610331) Error (cr-restore.c:1387): 18474 killed by signal 9: Killed
(00.637674) Error (cr-restore.c:2226): Restoring FAILED.
```

**Comment by avagin** [comment] 2017-03-14 22:43
How do you run a container? Did you specify tthe same volumes on restore?

**Comment by yogeshVU** [comment] 2017-03-15 02:49
Now I am trying to reproduce my previous error and I encounter another error in the process:
```
 sudo docker start --checkpoint --checkpoint-dir=/tmp/chkpoint/ kickcheck1 kickass_blackwell
You cannot restore multiple containers at once.
```

I created the container and checkpointed it in the --checkpoint-dir

**Comment by xemul** [comment] 2017-03-15 13:55
@yogeshVU after checkpoint, if you want to do _anything_ with the container but restore (i.e. -- start, or resume, or create another checkpoint) you need to commit your FS first. And before doing restore you need to restore one on the FS snapshot you've created with the checkpoint.

@boucher, shouldn't we put the FS ID into checkpoint directory with the image files, and on restore check that the restore happens on the proper FS?

**Comment by xemul** [comment] 2017-03-15 14:16
@yogeshVU , if you're doing just the commands about, the restore should go just fine, does it?

If you need to do anything after the "docker checkpoint create" one, it should look like

    docker run
    docker checkpoint create
    docker commit ... << this one, IIRC
    ...
    docker ... checkout? I don't know, what's the command to switch FS to the specified container ID?
    docker start --checkpoint

smth like this.

**Comment by yogeshVU** [comment] 2017-03-15 14:24
@Xemul thanks for the quick reply.What do you mean by switch FS? I am checkpointing a container by specifying the checkpoint-dir and leaving it to continue to run. say check1, check2....checkn. 
But, when I tried to do restore say at check1 I got the above error as shown in the logs in the main post.

I am going to start fresh checkpointing with a new container and will publish my update in short awhile.

**Comment by boucher** [comment] 2017-03-15 14:44
@yogeshVU You've got your command in the wrong order (the cause of your second problem). The checkpoint name needs to immediately follow `--checkpoint`. 

It should probably also be an error to call `docker start` on a container that is already running, so at the very least, you should stop the container before you try to restore it.

Finally, there's not currently a way to "atomically" checkpoint both the process and the filesystem. Ideally, you'd want to do this:

```
> docker pause looper
> docker checkpoint create --leave-running --checkpoint-dir=/tmp looper check1
> docker commit looper
# the output of this is now the image id you must use to create a new container
> docker unpause looper

> docker create --name looper2 <id>
> docker start --checkpoint check1 --checkpoint-dir=/tmp looper2 
```

However, CRIU does not currently support checkpointing a paused container, so you'll need to skip those steps, and "hope" that the filesystem is not modified between your calls to commit and checkpoint.

**Comment by yogeshVU** [comment] 2017-03-15 14:45
```
>> docker checkpoint create --checkpoint-dir=/tmp/chkpoint/ awesome_blackwell gitchk1
gitchk1

>> docker start --checkpoint --checkpoint-dir=/tmp/chkpoint/ gitchk1 awesome_blackwell

```

I got following error message:
```
You cannot restore multiple containers at once.
```

**Comment by yogeshVU** [comment] 2017-03-15 14:46
@boucher : thanks for the reply. Will try with the new commands once more.

**Comment by xemul** [comment] 2017-03-15 15:33
@boucher, thanks :)
And what's the issue with paused container? Does pausing mean freezing the cgroup?

**Comment by boucher** [comment] 2017-03-15 15:38
Yes, pause freezes the cgroup.

**Comment by yogeshVU** [comment] 2017-03-15 16:40
Ok Tried with following with an error dump. I issued first `pause` and then `create`

```

(checkpoint_proj) vagrant@vagrant:~/phoronix_docker/checkpoint_proj$ docker pause awesome_ritchie
WARNING: Error loading config file:/home/vagrant/.docker/config.json - stat /home/vagrant/.docker/config.json: permission denied
awesome_ritchie

(checkpoint_proj) vagrant@vagrant:~/phoronix_docker/checkpoint_proj$ docker checkpoint create --leave-running --checkpoint-dir=/tmp/chkpoint/ awesome_ritchie newtest1
WARNING: Error loading config file:/home/vagrant/.docker/config.json - stat /home/vagrant/.docker/config.json: permission denied
Error response from daemon: Cannot checkpoint container awesome_ritchie: rpc error: code = 2 desc = exit status 1: "criu failed: type NOTIFY errno 0\nlog file: /tmp/chkpoint/newtest1/criu.work/dump.log\n"


```

URL: https://gist.github.com/yogeshVU/d73ff39f94d2febdc0ebcc38899d916d

**Comment by xemul** [comment] 2017-03-15 18:31
@boucher, then criu supports that :) [--freeze-cgroup](https://criu.org/CLI/opt/--freeze-cgroup) option does this.

**Comment by boucher** [comment] 2017-03-15 18:48
Can I ask why a separate flag is needed? Is it impossible to auto detect?
Unfortunately adding new flags is a bit of a process -- it has to get
merged into each component separately.

**Comment by xemul** [comment] 2017-03-15 19:02
@boucher separate flag was needed because it was not 100% clear how to auto-detect. Taking a root task pid, then getting the cgroup for one and freezing the whole thing might not work well, as sometimes tasks sit in global cgroup and freezing it would freeze everything. Can you suggest some saner auto-detect logic for it?

**Comment by boucher** [comment] 2017-03-15 19:24
Hmm, I don't really know enough about the specifics. The issue isn't simply
detecting if the root process being checkpointed is currently in a frozen
state? That seems determinable by grabbing its cgroup and checking if it or
any of its parents is frozen, which seems available in /proc & /sys/fs?

**Comment by yogeshVU** [comment] 2017-03-16 11:22
How can I help to resolve this issue? Is there anything I can test to get more insights on the issue?

**Comment by yogeshVU** [comment] 2017-03-16 13:48
Also @boucher have the steps as mentioned in the https://github.com/xemul/criu/issues/293#issuecomment-286763593 been documented somewhere? Atleast I don't see it documented in the main docker readme  at https://github.com/docker/docker/blob/master/experimental/checkpoint-restore.md

**Comment by xemul** [comment] 2017-03-17 14:58
@yogeshVU , this is documented, but is not shouted out loud :) [Here's the article](https://criu.org/Filesystem_C/R), it's pretty short.

As far as the help is concerned, from my perspective the way to go would be to teach docker keep some rootFS ID in the images and refuse restoring on wrong roots. I've also created a feature request #294 to implement this on CRIU side.

**Comment by yogeshVU** [comment] 2017-03-17 15:17
Thanks @xemul : is there someway I can prevent this from happening.. so may be storing the snapshots on different working directory or something?

**Comment by xemul** [comment] 2017-03-17 15:27
@yogeshVU , yes, this is exactly what I'm talking about. We need some rootFS ID to be stored in or with images, that is to be checked on restore.

**Comment by tswift242** [comment] 2017-03-17 15:32
@xemul @yogeshVU I created this issue to docker with a proposal which covers this: https://github.com/docker/docker/issues/30507. It hasn't really gotten looked at. Any thoughts on how to get this more traction?

**Comment by xemul** [comment] 2017-03-17 15:37
Well, from the last comment in this issue it looks like @boucher already has the POC code. So probably getting one turning it into a PR would work. @boucher , how would you estimate the effort?

**Comment by boucher** [comment] 2017-03-17 15:39
There's no way really at the docker level to make this operation atomic,
without first adding in the cgroup-freeze flag -- docker really should only
automate this if it can guarantee (through pausing) that the filesystem
won't be changed.

**Comment by xemul** [comment] 2017-03-17 15:49
Can this be made inside the post-dump action-script? Since runc calls CRIU via RPC, the action-script will be notified to runc via the RPC socket. At the time this is called container is frozen.

**Comment by yogeshVU** [comment] 2017-03-17 16:11
hey @xemul the FS changes that you mentioned is that due to the external mounts to the docker container? or is it the files that are changing within the container?

**Comment by xemul** [comment] 2017-03-17 16:16
@yogeshVU , both matters, but AFAIU in your case files in container change.

**Comment by yogeshVU** [comment] 2017-03-17 16:37
@xemul  correct, since I am doing compilation task, my files do change in the container. so you are saying these files in the container are not checkpointed?

**Comment by xemul** [comment] 2017-03-17 16:41
@yogeshVU yes. This is what @boucher told -- you should do docker commit by hands. This probably can be automated and we're discussing it currently too.

**Comment by yogeshVU** [comment] 2017-03-17 16:45
@xemul  Thanks for more clarification !

**Comment by avagin** [comment] 2017-03-17 17:11
I would suggest to pass the  --cgroup-root options from runc, if a container has its own freeze cgroup. We will not to add any special options for that, so we will not need to fix containerd and docker.

I don't want to use a freezer cgroup in criu without any options, because we can't be sure that this group is belonged to a process tree.

**Comment by avagin** [comment] 2017-03-23 20:59
https://github.com/opencontainers/runc/pull/1355/commits/89b73a732c62847846aad48fcd061e20987d0a57

With this patch it is possible to pause a container, snapshot its file system and then checkpoint the container.

**Comment by yogeshVU** [comment] 2017-03-23 23:50
Hey @avagin , thats great! Can you list the step as in https://github.com/xemul/criu/issues/293#issuecomment-286763593 as to how I can use it to C/R using this? Will the steps remain same as in https://github.com/xemul/criu/issues/293#issuecomment-286763593?

**Comment by avagin** [comment] 2017-03-24 21:46
I think it should be something like this:
docker pause
docker checkpoint create
docker commit
docker unpause

**Comment by xemul** [comment] 2017-03-28 15:13
Hopefully this issue is resolved. Ways to handle "changed root" case is discussed in #289

**Closed by xemul** 2017-03-28 15:13 UTC
Labels: docker

**Comment by tswift242** [comment] 2017-04-19 18:25
@xemul @avagin @boucher Has there been any progress made on making checkpoint + commit more reliable? Either making it an atomic operation either at the criu or the docker/runc layer, or supporting checkpointing a paused docker container (or something else?). I am now frequently running into the "File <file> has bad size" error when doing the commit and checkpoint separately. Is there anything that can be done in the short term? Does this conversation belong in https://github.com/xemul/criu/issues/289?

**Comment by boucher** [comment] 2017-04-19 19:00
I would say that the conversation probably belongs at the docker level. The
issue you filed already is somewhat related, as is
https://github.com/moby/moby/issues/26856, but its possible we should
create a new issue.

**Comment by tswift242** [comment] 2017-04-19 19:36
@boucher I just realized, isn't the docker pause/unpause not necessary in the steps in https://github.com/xemul/criu/issues/293#issuecomment-286763593? If you just do the checkpoint and then the commit, won't that give the same behavior? After ```docker checkpoint create```, the container is stopped, and so the filesystem remains frozen. Then, you can do ```docker commit```  on the stopped container (unlike checkpoint create), which should always be consistent with the checkpoint. Or am I missing something?

Currently, I'm doing the commit before the checkpoint, which I think is why I'm having issues. Even when doing ```docker commit -p```, the container is still unpaused at the end of the command and so there is a window where the filesystem can change before the ```docker checkpoint create```. But reversing the order solves this I think, right?

**Comment by boucher** [comment] 2017-04-19 19:52
Yes, if you aren't using the --leave-running flag, then checkpointing then
committing should work fine.

**Comment by pmontrasio** [comment] 2017-04-26 13:24
It seems that stopping the container to take the snapshot can alter the file system. See [my comment](https://github.com/xemul/criu/issues/289#issuecomment-297378921) at #289

**Comment by xemul** [comment] 2017-05-02 09:23
@pmontrasio , yes, of course. The commit should be done while the container is frozen. E.g. you pause the container, then commit, then checkpoint, then unpause.

**Comment by vaidehip86** [comment] 2017-12-03 22:23
Hello,
I'm facing the same error , please help me to figure out
(00.640202)    196: Error (criu/files-reg.c:1528): Can't open file tmp/liblz4-java1595117645323586684.so on restore: No such file or directory
(00.640214)    196: Error (criu/files-reg.c:1463): Can't open file tmp/liblz4-java1595117645323586684.so: No such file or directory
(00.640218)    196: Error (criu/mem.c:513): Can't fixup VMA's fd
(00.641647)     54: Error (criu/cr-restore.c:1021): 196 exited, status=1
(00.650250) Error (criu/cr-restore.c:1024): 13121 killed by signal 9: Killed
(00.661342) mnt: Switching to new ns to clean ghosts
(00.661395) Error (criu/cr-restore.c:1890): Restoring FAILED.

I'm following the same steps commit checkpoint and restore still getting the error
sudo docker run --rm --name cont1 -h scale1.docker -p7077:7077 -p8080:8080 -i spark-cluster
sudo docker commit cont1 sample
sudo docker create --name cont2 sample
sudo docker checkpoint create --checkpoint-dir=/home/hiteshvm1/Documents/tmp/ cont1 chk1
sudo docker start --checkpoint-dir=/home/hiteshvm1/Documents/tmp/ --checkpoint=chk1 cont2

**Comment by adrianreber** [comment] 2017-12-04 06:44
@vaidehip86 your report seems unrelated to the original bug-report, but it seems you are missing temporary files in the restored container. Without knowing the details how you run the container it is hard to tell but mounting a tmpfs at /tmp could help as CRIU would then store the files of the tmpfs in the checkpoint and restore them later.

**Comment by vaidehip86** [comment] 2017-12-04 13:56
@adrianreber Thank you for your quick response but can you please explain me, more about how to mount tmpfs and when? and which details you need to explain me more about restore failure?

**Comment by adrianreber** [comment] 2017-12-04 15:41
@vaidehip86 Using Google I found this: ```docker run --tmpfs /tmp <name>``` 

I have not actually used it or tried it, but that sounds like it should do the 'right thing'.
