### ISSUE TITLE
restore failed for debain instance

### ISSUE THREAD

**Issue by chenhaiq** [xemul/criu#210] opened 2016-08-30 01:49 UTC
I reported this (https://github.com/lxc/lxc/issues/1156) to lxc last week, but it is more likely an issue in criu. 

To reproduce:

```
lxc-create -t download -n d1 -- -r wheezy -d debian -a amd64
# edit config to support checkpoint
lxc-start -n d1
lxc-checkpoint -n d1 -v -D /tmp/dump6 -s
lxc-checkpoint -n d1 -v -D /tmp/dump6 -r -o /tmp/dump6/lxc.log -l TRACE
```

log files:
https://pek3a.qingstor.com/oc-storage/dump.log
https://pek3a.qingstor.com/oc-storage/lxc.log
https://pek3a.qingstor.com/oc-storage/restore.log

```
lxc.include = /usr/share/lxc/config/debian.common.conf
lxc.arch = x86_64

# Container specific configuration
lxc.rootfs = /var/lib/lxc/d1/rootfs
lxc.rootfs.backend = dir
lxc.utsname = d1

# Network configuration
lxc.network.type = veth
lxc.network.link = lxcbr0
lxc.network.flags = up
lxc.network.hwaddr = 00:16:3e:7f:90:dd


lxc.console = none
lxc.tty = 0
lxc.cgroup.devices.deny = c 5:1 rwm
lxc.mount.auto = cgroup:mixed
lxc.autodev = 1
lxc.kmsg = 0
lxc.include = /usr/share/lxc/config/common.conf.d/00-lxcfs.conf
```

LXC is master code. 
ENV: ubuntu 16.04, 4.4.0-34-generic
lxc 2.0.4, lxcfs 2.0.3, criu 2.5

debain/jessie also fail in restore, but has different log:
https://pek3a.qingstor.com/oc-storage/dump_8027.log
https://pek3a.qingstor.com/oc-storage/lxc_dump_0827.log
https://pek3a.qingstor.com/oc-storage/lxc_restore_0827.log
https://pek3a.qingstor.com/oc-storage/restore_0827.log

**Comment by xemul** [comment] 2016-09-01 09:35
Cc @tych0

**Comment by tych0** [comment] 2016-09-08 00:17
Hi,

The second issue is a known issue; I'm hoping to fix it soon, but I've been on vacation for the last week and a half and so I'm just getting back :)

The first one is more interesting. Looking through the kernel source, I'm not sure exactly how it could happen. It looks like if you try and bind after setting the fanout it will fail with EINVAL, but the CRIU code doesn't do that. I can't see another obvious failure mode (besides structure sizing or something, but that's not it either, I don't think). I'll keep digging.

**Comment by tych0** [comment] 2016-09-14 16:12
Hi,

The second issue I believe is fixed with this: https://lists.openvz.org/pipermail/criu/2016-September/031497.html

and a patch series for liblxc that I have and will make a PR for when the above is agreed upon. The patch notes above also contain a more detailed description of the issue.

**Comment by xemul** [comment] 2016-11-03 23:24
So, can we close this one?

**Comment by tych0** [comment] 2016-11-03 23:30
I don't know. @chenhaiq can you provide a reproducer for the -EINVAL from sk-packet bind? I don't know how to reproduce that; the second issue is fixed, so we can close it if that is not reproducible.

**Comment by xemul** [comment] 2016-11-30 10:56
Hopefully the issue disappeared. If no -- feel free to re-open the issue.

**Closed by xemul** 2016-11-30 10:56 UTC
Labels: bug, dangling, LXC
