### ISSUE TITLE
Support for merged/unmerged controllers

### ISSUE THREAD

**Issue by sreekrishnapandi** [xemul/criu#318] opened 2017-05-29 15:19 UTC
I'm attempting to migrate a docker container between two hosts. however, I get an error stating: 
```
Error (criu/cgroup.c:1642): cg:     Can't mount controller dir .criu.cgyard.g3irYd/cpu,cpuacct: Device or resource busy
```

Here are my specs:
**Host 1:**

```
➜  ~ uname -a       
Linux ip-172-31-16-41 4.4.0-77-generic #98-Ubuntu SMP Wed Apr 26 08:34:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
➜  ~ 
➜  ~ docker -v      
Docker version 17.03.1-ce, build c6d412e
➜  ~ 
➜  ~ 
➜  ~ sudo criu check
Warn  (criu/autofs.c:77): Failed to find pipe_ino option (old kernel?)
Looks good.
```
**Host 2:**

```
➜  ~ uname -a
Linux mininet-vm 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
➜  ~ 
➜  ~ docker -v
Docker version 17.03.1-ce, build c6d412e
➜  ~ 
➜  ~ sudo criu check
Looks good.
```
Here's how to reproduce it:

**Host 1:**

```
➜  ~ docker run -d --name looper --security-opt seccomp:unconfined busybox \
         /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'
d830494e8bca353861c734a12854145fd9399b31f173a931e6cfdb529988dd06
➜  ~ docker checkpoint create --checkpoint-dir=/tmp looper cp1
```

Then I copy the /tmp/cp1 to the host 2.

**Host 2:**

```
➜  ~ docker create --name looper2 --security-opt seccomp:unconfined busybox \
         /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'
50d41c5580e4800b17b753c1ca8ecb011c142842002e467eb79111c4324e737e
➜  ~ docker start --checkpoint-dir=/tmp --checkpoint=cp1 looper2               
Error response from daemon: oci runtime error: criu failed: type RESTORE errno 0
log file: /tmp/cp1/criu.work/restore-2017-05-26T13:15:21-07:00/restore.log
```

Here's the **error log**

```
➜  ~ sudo tail /tmp/cp1/criu.work/restore-2017-05-26T13:15:21-07:00/restore.log
(00.000427) cg: rewriting docker/d830494e8bca353861c734a12854145fd9399b31f173a931e6cfdb529988dd06 to /docker/50d41c5580e4800b17b753c1ca8ecb011c142842002e467eb79111c4324e737e
(00.000430) cg: rewriting docker/d830494e8bca353861c734a12854145fd9399b31f173a931e6cfdb529988dd06 to /docker/50d41c5580e4800b17b753c1ca8ecb011c142842002e467eb79111c4324e737e
(00.000433) cg: rewriting docker/d830494e8bca353861c734a12854145fd9399b31f173a931e6cfdb529988dd06 to /docker/50d41c5580e4800b17b753c1ca8ecb011c142842002e467eb79111c4324e737e
(00.000436) cg: rewriting docker/d830494e8bca353861c734a12854145fd9399b31f173a931e6cfdb529988dd06 to /docker/50d41c5580e4800b17b753c1ca8ecb011c142842002e467eb79111c4324e737e
(00.000438) cg: rewriting docker/d830494e8bca353861c734a12854145fd9399b31f173a931e6cfdb529988dd06 to /docker/50d41c5580e4800b17b753c1ca8ecb011c142842002e467eb79111c4324e737e
(00.000442) cg: rewriting docker/d830494e8bca353861c734a12854145fd9399b31f173a931e6cfdb529988dd06 to /docker/50d41c5580e4800b17b753c1ca8ecb011c142842002e467eb79111c4324e737e
(00.000446) cg: Preparing cgroups yard (cgroups restore mode 0x4)
(00.000489) cg: Opening .criu.cgyard.g3irYd as cg yard
(00.000517) cg: 	Making controller dir .criu.cgyard.g3irYd/cpu,cpuacct (cpu,cpuacct)
(00.000555) Error (criu/cgroup.c:1642): cg: 	Can't mount controller dir .criu.cgyard.g3irYd/cpu,cpuacct: Device or resource busy
```

The same occurs if I migrate vice versa.

**Comment by xemul** [comment] 2017-05-31 06:06
Can you attach full dump and restore logs as well as 'cat /proc/cgroups' and 'cat /proc/self/cgroups' for both hosts?

**Comment by sreekrishnapandi** [comment] 2017-06-01 10:31
Host1:

```
➜  ~ cat /proc/cgroups
#subsys_name	hierarchy	num_cgroups	enabled
cpuset	1	7	1
cpu	2	7	1
cpuacct	3	7	1
blkio	4	7	1
memory	5	9	1
devices	6	7	1
freezer	7	7	1
net_cls	8	7	1
perf_event	9	7	1
net_prio	10	7	1
hugetlb	11	7	1

➜  ~ cat /proc/self/cgroup 
12:name=systemd:/user/1000.user/1.session
11:hugetlb:/user/1000.user/1.session
10:net_prio:/user/1000.user/1.session
9:perf_event:/user/1000.user/1.session
8:net_cls:/user/1000.user/1.session
7:freezer:/user/1000.user/1.session
6:devices:/user/1000.user/1.session
5:memory:/user/1000.user/1.session
4:blkio:/user/1000.user/1.session
3:cpuacct:/user/1000.user/1.session
2:cpu:/user/1000.user/1.session
1:cpuset:/
```

Host 2:

```
➜  ~ cat /proc/cgroups
#subsys_name	hierarchy	num_cgroups	enabled
cpuset	10	6	1
cpu	11	97	1
cpuacct	11	97	1
blkio	5	95	1
memory	3	115	1
devices	9	95	1
freezer	4	11	1
net_cls	2	8	1
perf_event	7	6	1
net_prio	2	8	1
hugetlb	8	6	1
pids	6	96	1
➜  ~ cat /proc/self/cgroup 
11:cpu,cpuacct:/user.slice
10:cpuset:/
9:devices:/user.slice
8:hugetlb:/
7:perf_event:/
6:pids:/user.slice/user-1000.slice
5:blkio:/user.slice
4:freezer:/user/ubuntu/0
3:memory:/user/ubuntu/0
2:net_cls,net_prio:/
1:name=systemd:/user.slice/user-1000.slice/session-726.scope


```

**Comment by avagin** [comment] 2017-06-01 21:11
```
Host 1
3:cpuacct:/user/1000.user/1.session
2:cpu:/user/1000.user/1.session

Host 2
11:cpu,cpuacct:/user.slice
```
The problem is that cpu and cpuacct are merged on the second host, but they are not merged on the first host.

**Comment by xemul** [comment] 2017-07-10 12:56
Actually a dup for issue #307

**Closed by xemul** 2017-07-10 12:56 UTC
Labels: new feature
