### ISSUE TITLE
lxc-checkpoint/criu dump fail: cannot dump /var/lib

### ISSUE THREAD

**Issue by timohl** [xemul/criu#317] opened 2017-05-21 21:05 UTC
Hi, I am trying to use lxc-checkpoint with lxc 2.0.7, criu 3.0, and custom linux 4.9.15 on centos7.

`lxc-checkpoint -D /tmp/checkpoint -n cont1 -o /tmp/lxc_log --logpriority=DEBUG`
This command fails with 
```
lxc-checkpoint: criu.c: do_dump: 1124 dump failed with 1
lxc-checkpoint: criu.c: do_dump: 1138 criu output: Will skip in-flight TCP connections

Checkpointing cont1 failed.
```

and the following logs:
[/tmp/lxc_log](https://gist.github.com/timohl/329e0fbd4a7083a1381e5c2cbf41edbf#file-lxc_log) and [/tmp/checkpoint/dump.log](https://gist.github.com/timohl/329e0fbd4a7083a1381e5c2cbf41edbf#file-dump-log).

Calling the criu dump with the parameters used by lxc-checkpoint plus -v4:
`/home/ohliger/shared/cluster/libvirt-lxctools/sbin/criu dump --tcp-established --file-locks --link-remap --manage-cgroups=full --ext-mount-map auto --enable-external-sharing --enable-external-masters --enable-fs hugetlbfs --enable-fs tracefs -D /tmp/checkpoint -o /tmp/checkpoint/dump.log --cgroup-root name=systemd:/lxc/cont1 --cgroup-root cpuset:/lxc/cont1 --cgroup-root memory:/lxc/cont1 --cgroup-root pids:/lxc/cont1 --cgroup-root hugetlb:/lxc/cont1 --cgroup-root perf_event:/lxc/cont1 --cgroup-root devices:/lxc/cont1 --cgroup-root cpu,cpuacct:/lxc/cont1 --cgroup-root net_cls:/lxc/cont1 --cgroup-root freezer:/lxc/cont1 --cgroup-root blkio:/lxc/cont1 --ext-mount-map /sys/fs/fuse/connections:sys/fs/fuse/connections -t 2518 --skip-in-flight --freeze-cgroup /sys/fs/cgroup/freezer///lxc/cont1 --force-irmap --leave-running -v4`
This results in the following log: [/tmp/checkpoint/dump.log](https://gist.github.com/timohl/329e0fbd4a7083a1381e5c2cbf41edbf#file-dump_v4-log)

I checked for the last error in the criu dump log and it seems there is a problem with handle 0x8bc8b which is 572555 in decimal. So, following issue #77 I searched for that inside the container resulting in the path /var/lib:
[file_info](https://gist.github.com/timohl/329e0fbd4a7083a1381e5c2cbf41edbf#file-file_info)

This is the lxc container config [cont1.config](https://gist.github.com/timohl/329e0fbd4a7083a1381e5c2cbf41edbf#file-var_lib_lxc_cont1_config) and some general system information [system_info](https://gist.github.com/timohl/329e0fbd4a7083a1381e5c2cbf41edbf#file-system_info),  especially containing `criu check --all` and `lxc-checkconfig`.

I would appreciate help regarding this issue.
If there is more information required, please let me know.

**Comment by xemul** [comment] 2017-05-22 09:09
You're right, this is due to inability to get path for fsnotified inode (dup of #147). You can handle this by adding an option '--irmap-scan-path /var/lib' to criu dump command.

**Comment by timohl** [comment] 2017-05-22 10:37
Thanks, '--irmap-scan-path /var/lib' (and due to a similar error '--irmap-scan-path /var') works for me.

What is exactly wrong with /var/lib and /var?
I do not use OverlayFS like in the referenced issue, but I use NFS.
Is this the issue?

**Comment by xemul** [comment] 2017-05-22 11:28
@timohl , the problem is that when some application opens an inotify (or fanotify) to monitor changes on some dir (or file) we can only get the inode number that's being monitored, while we need a path. And there's no effective way to get this path from inode. We have a code that scans pre-defined paths to find out which of them matches the found inode, but, as you see, it sometimes fails to find it :) Making it scan the whole FS is risky as dump can hang for ages :(

**Comment by xemul** [comment] 2017-05-22 20:10
So, since the original issue is resolved, I'll close this one (keeping in memory, that it's a dup of #147)

**Closed by xemul** 2017-05-22 20:10 UTC
Labels: bug, LXC
