### ISSUE TITLE
Support ghost files in alien (host) mount namespace

### ISSUE THREAD

**Issue by tswift242** [xemul/criu#139] opened 2016-03-17 19:42 UTC
I'm using boucher's experimental Docker build to checkpoint a Docker container. The main process inside this container uses SVNKit for SVN integration. SVNKit in turn uses JNA. Because of (what I believe is) an issue with JNA, a file of the form /tmp/jna--*/jna*.tmp is created and then subsequently deleted when my process boots, but the process still has an open file handle for this file. This causes the dump operation to fail when dumping this process:

Error (files-reg.c:1101): Can't lookup mount=46 for fd=-3 path=/tmp/jna--1071123326/jna7299404622010881251.tmp (deleted)

Running lsof on this process demonstrates the situation in the following line:

<process_name>  23219    10002  DEL    REG   202,1          933690 /tmp/jna--1071123326/jna7299404622010881251.tmp

Is there a way for criu to handle a situation like this more gracefully instead of failing? I realize that these processes are not behaving well, but it seems like maybe criu could be more fault tolerant to cases like this. What we have is a process with an open file handle to a deleted file; can we just ignore this file during the dump phase instead of erroring out? A question I have is how does this situation differ from what criu terms a "ghost file"? I don't see any references to ghost files in the dump log, so it doesn't seem like criu considers this to be a ghost file.

I can re-create this dump failure using the following contrived example:

1. Compile the attached c file: gcc -o test test.c
2. Run the following simple container, using the binary built above, and the attached shell script: docker run -d -v /tmp/test:/tmp/test -v /tmp/test.sh:/tmp/test.sh ubuntu /bin/bash -c '/tmp/test.sh'
3. Checkpoint the container: docker checkpoint <container_id>
4. Observer the same criu failure as above in the dump log.

I'm using criu 2.0 on ubuntu 14.04 with kernel 3.19.8.

[criu_test.zip](https://github.com/xemul/criu/files/178542/criu_test.zip)

**Comment by xemul** [comment] 2016-03-18 14:23
OK, so the problem is -- the opened and unlinked file (we call those ghost files) sit in another mount namespace. Yes, this is possible to fix it. Will try to do it soon :)

**Comment by avagin** [comment] 2016-03-18 18:06
I can't reproduce this issue:
https://asciinema.org/a/3ek6y9m80nkmej8eq2q7b0bpz

**Comment by tswift242** [comment] 2016-03-18 18:13
Hmm. I am able to reproduce this consistently with the steps above. The checkpoint operation always fails. Is it a kernel difference? I'm using kernel 3.19.8.

**Comment by avagin** [comment] 2016-03-18 18:15
[root@fc22-vm tmp]# uname -a
Linux fc22-vm 4.3.5-300.fc23.x86_64 #1 SMP Mon Feb 1 03:18:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by avagin** [comment] 2016-03-18 18:18
Could you execute your test and show me /proc/PID/fdinfo/FD and /proc/PID/mountinfo?
PID is a process id of the test process
FD is a file descriptor to a deleted file

**Comment by tswift242** [comment] 2016-03-18 18:58
Just tried again and the issue reproduced. Here's the output you requested:

root@ip-10-167-216-26:/tmp# cat /proc/10925/fdinfo/3
pos:    0
flags:  0100002
mnt_id: 46

 and

root@ip-10-167-216-26:/tmp# cat /proc/10925/mountinfo
85 50 0:37 / / rw,relatime - overlay overlay rw,lowerdir=/var/lib/docker/0.0/overlay/3242a1ba7a1fdc9ca15f158105ae3c0217e4db8766cc55ea0bf357b6e6114052/root,upperdir=/var/lib/docker/0.0/overlay/73bf578c2ee3293a78d66730a6c47d497f36eda46b7718db39826b4a200c2183/upper,workdir=/var/lib/docker/0.0/overlay/73bf578c2ee3293a78d66730a6c47d497f36eda46b7718db39826b4a200c2183/work
86 85 0:40 / /proc rw,nosuid,nodev,noexec,relatime - proc proc rw
87 85 0:41 / /dev rw,nosuid - tmpfs tmpfs rw,mode=755
88 87 0:42 / /dev/pts rw,nosuid,noexec,relatime - devpts devpts rw,gid=5,mode=620,ptmxmode=666
89 85 0:43 / /sys ro,nosuid,nodev,noexec,relatime - sysfs sysfs ro
90 89 0:44 / /sys/fs/cgroup ro,nosuid,nodev,noexec,relatime - tmpfs tmpfs ro,mode=755
91 90 0:25 /docker/cb4dd966ef66fa2133058672e0c32f283dfbcaafaf89f96e7985138d43012f41 /sys/fs/cgroup/cpuset ro,nosuid,nodev,noexec,relatime - cgroup cgroup rw,cpuset
92 90 0:26 /docker/cb4dd966ef66fa2133058672e0c32f283dfbcaafaf89f96e7985138d43012f41 /sys/fs/cgroup/cpu ro,nosuid,nodev,noexec,relatime - cgroup cgroup rw,cpu
93 90 0:27 /docker/cb4dd966ef66fa2133058672e0c32f283dfbcaafaf89f96e7985138d43012f41 /sys/fs/cgroup/cpuacct ro,nosuid,nodev,noexec,relatime - cgroup cgroup rw,cpuacct
94 90 0:28 /docker/cb4dd966ef66fa2133058672e0c32f283dfbcaafaf89f96e7985138d43012f41 /sys/fs/cgroup/memory ro,nosuid,nodev,noexec,relatime - cgroup cgroup rw,memory
95 90 0:29 /docker/cb4dd966ef66fa2133058672e0c32f283dfbcaafaf89f96e7985138d43012f41 /sys/fs/cgroup/devices ro,nosuid,nodev,noexec,relatime - cgroup cgroup rw,devices
96 90 0:30 /docker/cb4dd966ef66fa2133058672e0c32f283dfbcaafaf89f96e7985138d43012f41 /sys/fs/cgroup/freezer ro,nosuid,nodev,noexec,relatime - cgroup cgroup rw,freezer
97 90 0:31 /docker/cb4dd966ef66fa2133058672e0c32f283dfbcaafaf89f96e7985138d43012f41 /sys/fs/cgroup/net_cls ro,nosuid,nodev,noexec,relatime - cgroup cgroup rw,net_cls
98 90 0:32 /docker/cb4dd966ef66fa2133058672e0c32f283dfbcaafaf89f96e7985138d43012f41 /sys/fs/cgroup/blkio ro,nosuid,nodev,noexec,relatime - cgroup cgroup rw,blkio
99 90 0:33 /docker/cb4dd966ef66fa2133058672e0c32f283dfbcaafaf89f96e7985138d43012f41 /sys/fs/cgroup/perf_event ro,nosuid,nodev,noexec,relatime - cgroup cgroup rw,perf_event
100 90 0:34 /docker/cb4dd966ef66fa2133058672e0c32f283dfbcaafaf89f96e7985138d43012f41 /sys/fs/cgroup/net_prio ro,nosuid,nodev,noexec,relatime - cgroup cgroup rw,net_prio
101 90 0:35 /docker/cb4dd966ef66fa2133058672e0c32f283dfbcaafaf89f96e7985138d43012f41 /sys/fs/cgroup/hugetlb ro,nosuid,nodev,noexec,relatime - cgroup cgroup rw,hugetlb
102 90 0:36 / /sys/fs/cgroup/systemd ro,nosuid,nodev,noexec,relatime - cgroup systemd rw,name=systemd
103 85 202:1 /tmp/test /tmp/test rw,relatime - ext4 /dev/disk/by-uuid/81eb19c6-a16b-4db3-a07d-a3b5a9df2844 rw,data=ordered
104 85 202:1 /tmp/test.sh /tmp/test.sh rw,relatime - ext4 /dev/disk/by-uuid/81eb19c6-a16b-4db3-a07d-a3b5a9df2844 rw,data=ordered
105 85 202:1 /var/lib/docker/0.0/containers/cb4dd966ef66fa2133058672e0c32f283dfbcaafaf89f96e7985138d43012f41/resolv.conf /etc/resolv.conf rw,relatime - ext4 /dev/disk/by-uuid/81eb19c6-a16b-4db3-a07d-a3b5a9df2844 rw,data=ordered
106 85 202:1 /var/lib/docker/0.0/containers/cb4dd966ef66fa2133058672e0c32f283dfbcaafaf89f96e7985138d43012f41/hostname /etc/hostname rw,relatime - ext4 /dev/disk/by-uuid/81eb19c6-a16b-4db3-a07d-a3b5a9df2844 rw,data=ordered
107 85 202:1 /var/lib/docker/0.0/containers/cb4dd966ef66fa2133058672e0c32f283dfbcaafaf89f96e7985138d43012f41/hosts /etc/hosts rw,relatime - ext4 /dev/disk/by-uuid/81eb19c6-a16b-4db3-a07d-a3b5a9df2844 rw,data=ordered
108 87 0:38 / /dev/shm rw,nosuid,nodev,noexec,relatime - tmpfs shm rw,size=65536k
109 87 0:15 / /dev/mqueue rw,nosuid,nodev,noexec,relatime - mqueue mqueue rw
51 86 0:40 /bus /proc/bus ro,nosuid,nodev,noexec,relatime - proc proc rw
52 86 0:40 /fs /proc/fs ro,nosuid,nodev,noexec,relatime - proc proc rw
53 86 0:40 /irq /proc/irq ro,nosuid,nodev,noexec,relatime - proc proc rw
54 86 0:40 /sys /proc/sys ro,nosuid,nodev,noexec,relatime - proc proc rw
55 86 0:40 /sysrq-trigger /proc/sysrq-trigger ro,nosuid,nodev,noexec,relatime - proc proc rw
56 86 0:41 /null /proc/kcore rw,nosuid - tmpfs tmpfs rw,mode=755
57 86 0:41 /null /proc/timer_stats rw,nosuid - tmpfs tmpfs rw,mode=755

**Comment by tswift242** [comment] 2016-03-18 19:02
May be important to mention, that, as you can see above, I'm using the overlay storage driver for Docker. I've seen a couple issues on here related to overlayfs; does criu not have good support for overlayfs?

Here's my full docker info if it helps:

root@ip-10-167-216-26:/tmp# docker info
Containers: 1
Images: 39
Server Version: 1.10.0-dev
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.19.8-031908-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.675 GiB
Name: ip-10-167-216-26
ID: BHIU:R4HK:JKYC:U6DA:CVNB:HONO:FSD5:VO22:Q64H:YWYD:TWN6:DTUF
Debug mode (server): true
 File Descriptors: 18
 Goroutines: 33
 System Time: 2016-03-18T19:01:06.109006488Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/bin/docker
 Docker Root Dir: /var/lib/docker/0.0
WARNING: No swap limit support
Experimental: true

**Comment by avagin** [comment] 2016-03-18 20:16
Yes, you are right. This issue depends on overlayfs.
Cc: @gablg1

**Comment by avagin** [comment] 2016-03-18 21:31
I switched on overlayfs and everything works for me too. Looks like it's due to a kernel bug, which was fixed in the 4.2 kernel:
http://comments.gmane.org/gmane.linux.file-systems.union/236

**Comment by gablg1** [comment] 2016-03-19 02:02
Yes. I added the --overlays flag a while ago to circumvent this bug within
CRIU. It works but it's not thoroughly tested as far as I know.

**Closed** 2016-03-24 11:17 UTC
Labels: bug
