### ISSUE TITLE
criu 2.7 checkpoint regression: "binfmt_misc isn't mount on the host"

### ISSUE THREAD

**Issue by tswift242** [xemul/criu#235] opened 2016-10-21 21:17 UTC
After upgrading from criu 2.6 to 2.7, checkpointing my Docker container now fails with "Error (criu/kerndat.c:201): binfmt_misc isn't mount on the host". I've also tried building and using the latest from the criu-dev branch (GitID: v2.7-307-g6d56b42), which gave the same error.

The dump log is attached 
[dump.txt](https://github.com/xemul/criu/files/545235/dump.txt)

I'm using Linux kernel 4.4.25 and Docker 1.13.0-dev experimental.

**Comment by avagin** [comment] 2016-10-21 21:18
Cc: @tkhai

**Comment by tkhai** [comment] 2016-10-24 09:09
The situation is clear for me. Recent criu forces mounting of binfmt_misc, while old versions doesn't.
@tswift242 really doesn't have binfmt_misc mounted on host, so generic code fails. If he had had a binfmt_misc partition mounted inside CT on old criu, there would have been the same problem.

So, the reason is in generic code. If it's a real problem? According by kerndat design it's not.

**Comment by xemul** [comment] 2016-10-24 11:17
@tkhai , I don't understand the reason of failure in the first place. Can you elaborate?

**Comment by tkhai** [comment] 2016-10-24 11:32
I see only 
$ grep Err /tmp/mozilla_kirill0/dump.txt 
(01.384914) Error (criu/kerndat.c:201): binfmt_misc isn't mount on the host
(01.404165) Error (criu/cr-dump.c:1636): Dumping FAILED.

What is the first place you mean?

**Comment by xemul** [comment] 2016-10-24 11:35
"In the first place" means "в первую очередь" :)

So what's the reason for failure? CRIU have found binfmt mount in container and couldn't check whether it's virtualized or not on host because it's not there?

**Comment by tkhai** [comment] 2016-10-24 11:40
I've just tried to speak from my heart in English :)

Yes, this is the reason. I've reproduced that by umounting host's binfmt_misc on my node.

**Comment by xemul** [comment] 2016-10-24 11:53
Hm... But @tswift242 says that with 2.6 there were no such problem, while binfmt_misc checker was there.

**Comment by tkhai** [comment] 2016-10-24 12:02
I did git checkout 090bcd01039aec6ecf4063eb599f7ec5540036c2
Author: Pavel Emelyanov <xemul@virtuozzo.com>
Date:   Mon Sep 12 12:44:04 2016 +0300

    criu: Version 2.6
    
    So, this time we have quite a lot of new features for a monthly
    release cadence, including --leave-stopped on restore, TMEM for
    PPC and shmem changes tracking.
    
    Also bugfixes, of course, and a little bit more deprecations.
    
    Signed-off-by: Pavel Emelyanov <xemul@virtuozzo.com>

kirill@pro:~/criu$ git grep add_cr_time_mount criu/mount.c
kirill@pro:~/criu$

**Comment by xemul** [comment] 2016-10-24 12:25
Ah, so the reason for failure is "criu DIDN'T find bfmtmisc mount in container MOUNTED one and then failed to check whether IT is virtualized or not"?

**Comment by tkhai** [comment] 2016-10-24 12:29
"criu didn't find binfmt_misc on host (the enviroment, where criu binary is executed), and then failed to check whether IT is virtualized or not"

So, the fast solution is just to mount binfmt_misc on host.

**Comment by xemul** [comment] 2016-10-24 12:33
It is, would you cook a patch for it?

**Comment by tkhai** [comment] 2016-10-24 12:38
Hm. Just mount in criu mnt_ns and do not umount? Can we confuse some soft if we umount it?
Say,
1)criu mounts
2)programA checks for binfmt_misc
3)criu umounts
4)programA tryes to use binfmt_misc and fails

**Comment by xemul** [comment] 2016-10-24 12:49
Yes it can be such. What are your suggestions?

The thing is that most of the binfmt misc code we have is only needed by vzkernel and in existing form it confuses all other users.

If we could make criu by default not mess with all this binfmt misc stuff, and provide an option (or environment variable) to turn it on (it will be turned on by vz software) that'd be awesome.

**Comment by tkhai** [comment] 2016-10-24 12:53
My suggestion is to mount always binfmt_misc on host and do not umount it at all. So, we don't have problems with host's software and have a possibility to check virtualized partitions in vzkernel

**Comment by xemul** [comment] 2016-10-24 12:53
OK. Let's make a patch for it :)

**Comment by avagin** [comment] 2016-10-24 17:00
I don't like an idea to mount something on a host side. Why we don't want to add an option for dumping binfmt_misc. binfmt_misc is virtualized only in OpenVZ and we don't know how it will be virtualized in the upstream kernel. It's another reason to have an option.

**Comment by xemul** [comment] 2016-10-24 17:02
I agree. Can you suggest the way to ship this into criu w/o breaking vz tool set?

**Comment by avagin** [comment] 2016-10-25 18:21
We can always enable this option, if we have the /proc/vz/ directory

**Comment by xemul** [comment] 2016-11-01 03:19
Gents, here's my plan how to deal with this in 2.8 (this November): https://lists.openvz.org/pipermail/criu/2016-October/032682.html

**Comment by xiaozhazi** [comment] 2016-11-01 04:26
I have the same problem with you. It's very strange, I have two machine, this one shows the problem, but worked well in another machine. The criu version and docker version is same.

**Comment by xemul** [comment] 2016-11-03 04:54
Will be fixed in 2.8

**Closed by xemul** 2016-11-03 04:54 UTC
Labels: bug
