### ISSUE TITLE
docker checkpoint failed

### ISSUE THREAD

**Issue by kimh** [xemul/criu#6] opened 2015-07-15 15:06 UTC
I'm trying to make `docker checkpoint` works, but I got the following error.

Here is the docker client log.

```
vagrant@vagrant-ubuntu-trusty:~/docker$ export CID=$(docker run -d busybox:latest /bin/sh -c 'i=0; while true; do echo $i >> /foo; i=$(e
xpr $i + 1); sleep 3; done')

vagrant@vagrant-ubuntu-trusty:~/docker$ docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS               NAMES
806b0fa36744        busybox:latest      "/bin/sh -c 'i=0; wh   3 seconds ago       Up 1 seconds                            determined_visvesvaraya

vagrant@vagrant-ubuntu-trusty:~/docker$ docker checkpoint $CID
Error response from daemon: Cannot checkpoint container 806b0fa36744339b60e41727c1c7f4aa65e30cd3ab86a63206cae9c4854b6fbb: criu failed: type NOTIFY errno 0
```

Here is the docker daemon log.

```
INFO[0840] POST /v1.20/containers/806b0fa36744339b60e41727c1c7f4aa65e30cd3ab86a63206cae9c4854b6fbb/checkpoint
ERRO[0840] Handler for POST /containers/{name:.*}/checkpoint returned error: Cannot checkpoint container 806b0fa36744339b60e41727c1c7f4aa65e30cd3ab86a63206cae9c4854b6fbb: criu failed: type NOTIFY errno 0
ERRO[0840] HTTP Error                                    err=Cannot checkpoint container 806b0fa36744339b60e41727c1c7f4aa65e30cd3ab86a63206cae9c4854b6fbb: criu failed: type NOTIFY errno 0 statusCode=500
```

Here is my environment.

Ubuntu: 14.04 (vagrant)

criu
```
vagrant@vagrant-ubuntu-trusty:~/docker$ criu --version
Version: 1.6
GitID: v1.6-95-gde70936
```

docker https://github.com/boucher/docker/commit/dd06ea04a3bbe0305c512834b2c313e0d0babd4b
```
vagrant@vagrant-ubuntu-trusty:~/docker$ docker -v
Docker version 1.8.0-dev, build dd06ea0
```

Please let me know if you need more information.

**Comment by xemul** [comment] 2015-07-15 15:39
Can you find dump logs?
Also adding @boucher to discussion :)

**Comment by boucher** [comment] 2015-07-15 16:11
Hey @kimh, there's currently a regression in Docker thats causing the problem. Reverting this commit should work as a temporary fix: f18fb5b3efd59d54c00d4e1b1d4b88c4b21e96be

**Comment by kimh** [comment] 2015-07-15 16:16
@boucher ok, reverted and now compiling....It's totally different discussion, but are there any good ways to compile docker fast? Using `make` create docker image everytime from scratch :(

**Comment by boucher** [comment] 2015-07-15 16:19
When you build with make docker should be using its cache for everything
but the final step. My builds take less than a minute usually.

On Wednesday, July 15, 2015, Kim, Hirokuni <notifications@github.com> wrote:

> @boucher <https://github.com/boucher> ok, reverted and now
> compiling....It's totally different discussion, but are there any good ways
> to compile docker fast? Using make create docker image everytime from
> scratch :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xemul/criu/issues/6#issuecomment-121666031>.
>


-- 
Sent from Gmail Mobile

**Comment by kimh** [comment] 2015-07-15 16:30
@boucher Looks now `docker checkpoint` is not available.

```
vagrant@vagrant-ubuntu-trusty:~/docker$ docker -v
Docker version 1.8.0-dev, build f18fb5b
vagrant@vagrant-ubuntu-trusty:~/docker$ docker checkpoint
docker: 'checkpoint' is not a docker command.
See 'docker --help'.
```

Did I have to use different version of docker binary ? (daemon with reverted version and client with latest)

**Comment by boucher** [comment] 2015-07-15 16:36
Are you sure you applied the revert to the right branch?

**Comment by kimh** [comment] 2015-07-15 16:39
Doesn't this look so?

```
vagrant@vagrant-ubuntu-trusty:~/docker$ docker -v
Docker version 1.8.0-dev, build f18fb5b
```

**Comment by kimh** [comment] 2015-07-15 16:40
Oh, I think I misunderstood what you said. So reiterate just in case, I have to revert `f18fb5b3efd59d54c00d4e1b1d4b88c4b21e96be` commit?

**Comment by boucher** [comment] 2015-07-15 16:40
Yes, from the cr-combined branch.

**Comment by kimh** [comment] 2015-07-15 16:47
@boucher Now checkpoint works. However, restore doesn't.

```
docker restore db490e9a820014dca0c6e960b28381db7bc0dcf5778fcb6e68bc855fb96465c0
```

```
ERRO[0045] Error restoring container: criu failed: type NOTIFY errno 0, exitCode={-1 %!d(bool=false)}
ERRO[0045] Handler for POST /containers/{name:.*}/restore returned error: Cannot restore container db490e9a820014dca0c6e960b28381db7bc0dcf5778fcb6e68bc855fb96465c0: criu failed: type NOTIFY errno 0
ERRO[0045] HTTP Error                                    err=Cannot restore container db490e9a820014dca0c6e960b28381db7bc0dcf5778fcb6e68bc855fb96465c0: criu failed: type NOTIFY errno 0 statusCode=500
INFO[0050] GET /v1.20/containers/json
```

Any idea?

**Comment by boucher** [comment] 2015-07-15 16:51
Can you pass --work-dir=/tmp/something to the restore and then paste the
criu restore log somewhere

**Comment by kimh** [comment] 2015-07-15 17:01
Is restore.log supposed to be created under `/tmp/something` ?

```
docker restore $CID  --work-dir=/tmp/something
Error response from daemon: Cannot restore container e50472b26a0ce9e1369d0f76e5b25d11e68979709691b7dc66cf305cd18670df: a container has already joined the endpoint
Error response from daemon: no such id: --work-dir=/tmp/something
Error: failed to restore one or more containers
```

Looks like nothing is created.

```
vagrant@vagrant-ubuntu-trusty:/var$ ls /tmp/something
ls: cannot access /tmp/something: No such file or directory
```

Even if I first created something directory, nothing is created.

**Comment by boucher** [comment] 2015-07-15 17:05
You must pass --work-dir before the $CID

**Comment by kimh** [comment] 2015-07-15 17:11
Here is restore.log

https://gist.github.com/kimh/1077ad2a8e7aa58f3eed

**Comment by boucher** [comment] 2015-07-15 17:23
Did you build criu from source? I believe there's a bug in the master branch that @xemul is working on (and may already have a patch for?)

**Comment by kimh** [comment] 2015-07-15 17:32
Yes, I built from source. My HEAD is https://github.com/xemul/criu/commit/de70936ec74df0cde1a04a9704b3747aa452d084

I live in JST, so I'll go to bed now. @xemul can you let me know if there is anything that I can try?

Thank you for your quick help @boucher

**Comment by boucher** [comment] 2015-07-15 18:54
https://github.com/opencontainers/runc/pull/130

I believe this is tracking the fix in runc, but it will then need to be merged into docker master as well.

**Comment by YaoZengzeng** [comment] 2015-07-19 04:43
Hi,@boucher what do you mean "Reverting this commit should work as a temporary fix: f18fb5b3efd59d54c00d4e1b1d4b88c4b21e96be".
I'm under cr-combined branch and "git rest --hard f18fb5b3efd59d54c00d4e1b1d4b88c4b21e96be" ,then compile ,but the binary seems not support checkpoint and restore.
root@iZu1pbgsilbZ:~# docker version 
Client:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f18fb5b
 Built:        Sun Jul 19 03:16:51 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f18fb5b
 Built:        Sun Jul 19 03:16:51 UTC 2015
 OS/Arch:      linux/amd64
My problem is same with @kimh.

**Comment by boucher** [comment] 2015-07-19 04:51
Sorry, as of yesterday it's now behind the experimental flag. You need to
build with DOCKER_EXPERIMENTAL=1

Also the fix has been incorporated so reverting that commit is no longer
necessary. However, there is a new blocker that has not yet been figured
out.

On Saturday, July 18, 2015, YaoZengzeng <notifications@github.com> wrote:

> Hi,@boucher <https://github.com/boucher> what do you mean "Reverting this
> commit should work as a temporary fix:
> f18fb5b3efd59d54c00d4e1b1d4b88c4b21e96be".
> I'm under cr-combined branch and "git rest --hard
> f18fb5b3efd59d54c00d4e1b1d4b88c4b21e96be" ,then compile ,but the binary
> seems not support checkpoint and restore.
> root@iZu1pbgsilbZ:~# docker version
> Client:
> Version: 1.8.0-dev
> API version: 1.20
> Go version: go1.4.2
> Git commit: f18fb5b
> Built: Sun Jul 19 03:16:51 UTC 2015
> OS/Arch: linux/amd64
>
> Server:
> Version: 1.8.0-dev
> API version: 1.20
> Go version: go1.4.2
> Git commit: f18fb5b
> Built: Sun Jul 19 03:16:51 UTC 2015
> OS/Arch: linux/amd64
> My problem is same with @kimh <https://github.com/kimh>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xemul/criu/issues/6#issuecomment-122625309>.
>


-- 
Sent from Gmail Mobile

**Comment by YaoZengzeng** [comment] 2015-07-19 05:03
@boucher  I compile like this
 "root@iZu1pbgsilbZ:/home/monster/docker# make DOCKER_EXPERIMENTAL=1 binary",
and the result support checkpoint and restore command .But checkpoint still doesn't work

root@iZu1pbgsilbZ:/home/monster/docker# docker checkpoint $CID
Error response from daemon: Cannot checkpoint container be9da3d14c883491fee1d73a727b88d9d52e1db82996f9110080a544ade94b24: criu failed: type NOTIFY errno 0
Error: failed to checkpoint one or more containers

**Comment by boucher** [comment] 2015-07-19 15:59
Yes, things are currently broken. You can follow this thread on the mailing
list:
http://lists.openvz.org/pipermail/criu/2015-July/021277.html

**Comment by YaoZengzeng** [comment] 2015-07-20 05:07
Hi @boucher  I find that in docker 1.8.0 ,it will not create dockerinit-1.8.0-dev under /var/lib/docker/init/ or anywhere else .I don't if it is a bug or something else ....Becasuse of this ,I even can't do external C/R test in docker 1.8.0,the docker_cr.sh will report the missing of dockerinit-1.8.0-dev.

**Comment by xemul** [comment] 2015-07-22 11:40
@kimh the error you see in logs should be fixed in recent head. The fixing commit is 7b20f42f785bafcc61c11adddcdbf2d5a54917cf

**Comment by kimh** [comment] 2015-07-22 12:10
@xemul thank you for the ping. I'll try later

**Comment by kimh** [comment] 2015-07-26 12:14
@xemul I tried 7b20f42f785bafcc61c11adddcdbf2d5a54917cf and restore once has worked. Then, I updated docker to use https://github.com/boucher/docker/commit/24e477bdb8865ce30f2bb332b34d01f9a42215f5 and now checkpoint doesn't work... (DOCKER_EXPERIMENTAL is set).

The head for CRIU is https://github.com/xemul/criu/commit/ace699d7633f36247ab63d2dbc96187a763c9f4a

Here is the log for failed checkpoint which is useless.

```
vagrant@vagrant-ubuntu-trusty:~/criu$ docker checkpoint $CID
Error response from daemon: Cannot checkpoint container 94dd8db31db80dc3cc61c44cab05b6018595c0b48144350b82e191897177bae4: criu failed: type NOTIFY errno 0
Error: failed to checkpoint one or more containers
```

How can I get criu dump log?

**Comment by xemul** [comment] 2015-07-27 09:06
OK :) Now we need the @boucher 's help with Docker part.

**Comment by boucher** [comment] 2015-07-27 16:47
The dump log should be at /var/run/docker/execdriver/native/<container_id>/criu.work/dump.log

**Comment by kimh** [comment] 2015-07-27 16:59
@boucher [here](https://gist.github.com/kimh/8c0b2e49c78e469fb8ba) is the dump.log

**Comment by boucher** [comment] 2015-07-27 17:16
This is the same issue as before, in Docker. The fix has not yet made its way from libcontainer to docker. You can update libcontainer yourself for now, or you can try reverting the same commit from the top of this thread.

**Comment by kimh** [comment] 2015-07-27 17:23
@boucher cool, now it worked.

> Also the fix has been incorporated so reverting that commit is no longer
I thought I don't need to revert the commit anymore.

**Comment by boucher** [comment] 2015-07-27 17:26
Ahh, sorry, my apologies. The issue actually has two components to it, and one got fixed which exposed the second, which got fixed in a later commit that hasn't yet been merged into docker.

**Comment by LK4D4** [comment] 2015-07-27 21:29
@xemul I hit same error with `type NOTIFY`. It's pretty weird because it's okay for some machines, but not for another(also maybe you know what could be different?). Also it seems like serious fix, could you tag `1.6.1`?

**Comment by xemul** [comment] 2015-07-28 10:26
Well, 1.6.1 is not needed to deliver 7b20f42, since the breakage happened after 1.6 as well :)
I've read this thread again and can't see why plain 1.6 doesn't work for you :( Or does it?

**Comment by LK4D4** [comment] 2015-07-28 16:09
@xemul yes, 1.6 doesn't work for me. Actually original issue was about 1.6 as well. Maybe something was occasionally fixed in master :) I'll try to build master and report here.

**Comment by boucher** [comment] 2015-07-28 16:48
It might also be worth checking if 1.5.3 works, since I believe that is our
minimum required version of criu?

On Tue, Jul 28, 2015 at 9:09 AM, Alexander Morozov <notifications@github.com

**Comment by LK4D4** [comment] 2015-07-28 16:52
@xemul @boucher It's actually doesn't work with master either. I think it can be something about systemd. I see next lines in dump:
```
(00.113525) Dumping mountpoints
(00.113528)     237: 3f:/null @ ./proc/kcore
(00.113554)     235: 3e:/bus @ ./proc/bus
(00.113557)     231: 3e:/irq @ ./proc/irq
(00.113559)     230: 3e:/sysrq-trigger @ ./proc/sysrq-trigger
(00.113560)     229: 3e:/sys @ ./proc/sys
(00.113561)     305: 1f:/user.slice/busybox @ ./sys/fs/cgroup/memory
(00.113563)     304: 1e:/user.slice/busybox @ ./sys/fs/cgroup/freezer
(00.113565)     303: 1d:/user.slice/busybox @ ./sys/fs/cgroup/hugetlb
(00.113566)     302: 1c:/user.slice/busybox @ ./sys/fs/cgroup/net_cls,net_prio
(00.113568)     301: 1b:/user.slice/busybox @ ./sys/fs/cgroup/perf_event
(00.113569)     300: 1a:/user.slice/busybox @ ./sys/fs/cgroup/devices
(00.113570)     299: 19:/user.slice/busybox @ ./sys/fs/cgroup/cpu,cpuacct
(00.113572)     298: 18:/user.slice/busybox @ ./sys/fs/cgroup/cpuset
(00.113573)     297: 17:/user.slice/busybox @ ./sys/fs/cgroup/blkio
(00.113575)     296: 16:/user.slice/user-1000.slice/session-1.scope @ ./sys/fs/cgroup/systemd
(00.113576)     295: 47:/ @ ./sys/fs/cgroup
(00.113578) Something is mounted on top of ./sys/fs/cgroup
(00.113602) Error (mount.c:1005): Can't create a temporary directory: Read-only file system
(00.113675) Unlock network
(00.113677) Running network-unlock scripts
(00.113686)     RPC
(00.113767) Unfreezing tasks into 1
(00.113770)     Unseizing 28168 into 1
(00.113792) Error (cr-dump.c:1996): Dumping FAILED.
```

**Comment by boucher** [comment] 2015-07-28 16:53
And, this is runc, not docker?

On Tue, Jul 28, 2015 at 9:52 AM, Alexander Morozov <notifications@github.com

**Comment by LK4D4** [comment] 2015-07-28 16:54
@boucher Yup, pure runc.

**Comment by LK4D4** [comment] 2015-07-28 17:06
@xemul @boucher So, I mounted "tmpfs" on "/tmp" inside container(which is sorta weird too). Now I have problem that I built-in `sit` module in kernel and now I have `sit` interface in each network namespace. I think we should probably just skip it. WDYT?

**Comment by LK4D4** [comment] 2015-07-28 17:28
I was able to checkpoint with patch:
```
diff --git a/net.c b/net.c
index 082ccb6..c5e0ee6 100644
--- a/net.c
+++ b/net.c
@@ -288,6 +288,8 @@ static int dump_one_link(struct nlmsghdr *hdr, void *arg)
        case ARPHRD_VOID:
                ret = dump_one_voiddev(ifi, kind, tb, fds);
                break;
+       case ARPHRD_SIT:
+               break;
        default:
 unk:
                ret = dump_unknown_device(ifi, kind, tb, fds);
```
I think probably real problem is that criu writes too cryptic errors in stderr, which confuses people :)

**Comment by xemul** [comment] 2015-07-29 08:31
OK, this
   Error (mount.c:1005): Can't create a temporary directory: Read-only file system
is because /tmp is read-only. CRIU tries to create a temp dir there to dump tmpfs contents.

As far as the SIT is concerned. The patch you' ve mentioned is not complete :) SIT device has a configuration that has to be dumped too, that's why we check device types one by one.

And, finally, about cryptic errors -- I fully agree :D Any ideas (and patches) improving those are always warmly welcome!

**Comment by xemul** [comment] 2015-07-29 08:33
I've created an issue #10 for tmpfs case. BTW, this patch should workaround it:
--- a/mount.c
+++ b/mount.c
@@ -999,7 +999,7 @@ static int open_mountpoint(struct mount_info *pm)
 		goto out;
 
 	mnt_path = mkdtemp(mnt_path_tmp);
-	if (mnt_path == NULL && errno == ENOENT)
+	if (mnt_path == NULL)
 		mnt_path = mkdtemp(mnt_path_root);
 	if (mnt_path == NULL) {
 		pr_perror("Can't create a temporary directory");

**Comment by xemul** [comment] 2015-07-29 08:35
And issue #11 is about SIT device support.

**Comment by LK4D4** [comment] 2015-07-29 15:40
@xemul Thanks! I think you can close this issue, because now it's only confusing to read this thread about four different errors :)

**Comment by xemul** [comment] 2015-07-29 16:29
OK, @kimh , AFAIU you're issue is finally fixed. If no, just lest us know :)

**Closed by xemul** 2015-07-29 16:29 UTC

**Comment by klesgidis** [comment] 2015-08-02 11:34
Hello! First of all thanks for all of your help. I am trying to checkpoint a container but I get the error 
<code>criu failed: type NOTIFY errno 0.</code>
 I have criu 
<code>1.6 compiled from source</code>
 and docker
<code>Client:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   24e477b
 Built:        Sun Aug  2 11:18:41 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   24e477b
 Built:        Sun Aug  2 11:18:41 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true
</code>
I tried to follow the conversation but any of your suggestions didn't help. Is there any other advice or update that I can try? 
Thank you

**Comment by LK4D4** [comment] 2015-08-02 17:16
@klesgidis criu doesnt' work with latest docker now

**Comment by klesgidis** [comment] 2015-08-02 18:14
@LK4D4  thanks for your reply. Is there any configuration that I can use? (Docker & CRIU version). 
I tried the above recommended commits but I couldn't C/R a container.

**Comment by xemul** [comment] 2015-08-03 12:51
Can we create the new issue for this instead of creating additional mess inside the closed one.

**Comment by klesgidis** [comment] 2015-08-03 16:13
@xemul do you want me to open another issue and delete the above messages?

Thanks

**Comment by xemul** [comment] 2015-08-03 18:32
@klesgidis , to open another issue :) And (while opening) please attach criu dump and/or restore logs you have. Thanks.

**Comment by Vallari-Mehta** [comment] 2016-06-08 23:41
I am trying to build docker from following source: https://github.com/boucher/docker.git and using the branch: /cr-combined. But I do not see docker checkpoint option.

![screen shot 2016-06-08 at 6 37 08 pm](https://cloud.githubusercontent.com/assets/3595018/15914633/24c1f750-2da8-11e6-83dd-75e653488729.png)

I am using the command make DOCKER_EXPERIMENTAL=1 build to build the docker 
And  then make DOCKER_EXPERIMENTAL=1 binary to compile.

After compiling when I try running the compiled binary: ./docker --help. 
I do not see any checkpoint option.
I also tried ./docker checkpoint. But it says "docker: 'checkpoint' is not a docker command."

Please let me know if you need any information.

**Comment by xemul** [comment] 2016-06-09 13:26
Please, open another issue if you have problems. This one is closed already.
