### ISSUE TITLE
OCI run time error while restoring postgres container from checkpoint

### ISSUE THREAD

**Issue by bhaktibohara** [xemul/criu#320] opened 2017-06-05 22:33 UTC
These are the steps I followed : 

On server 1 : Create a postgres container using this command 

$ docker run --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -d postgres

next I ran psql 
$ docker run -it --rm --link some-postgres:postgres postgres psql -h postgres -U postgres

and added a database and a table and single entry to the table 

I logged out of psql and checkpointed the postgres container. All good till here.

When I restored the container on same machine , I see error in restore.log file as 

![image](https://cloud.githubusercontent.com/assets/14326259/26806108/fd769c7c-4a03-11e7-9b39-869e1958d06e.png)

Same thing happens , if I copy the checkpoint directory to a different machine, 

On machine 2 : I create same container.  checkpoint it (to avoid issues with freshly created containers) and then restore from the checkpoint from machine 1. It still gives the same error. 

Can you please help me understand what I am doing wrong. 

Regards
Bhakti

**Comment by bhaktibohara** [comment] 2017-06-05 22:36
This is similar to https://github.com/xemul/criu/issues/300 I guess. Let me know.

**Comment by xemul** [comment] 2017-06-06 12:15
It looks like #300 indeed. Ccing @avagin .

**Comment by xemul** [comment] 2017-06-15 10:30
@avagin , please :)

**Comment by avagin** [comment] 2017-06-15 23:00
Docker doesn't dump a content of /dev/shm

**Comment by avagin** [comment] 2017-06-15 23:27
The problem is that the /dev/shm mount is an external mount for the container. It was initially mounted by docker on the host side and only then it was bind-mounted to the container.

```
[root@localhost ~]# cat /proc/*/mountinfo | grep 0:95 | sort | uniq
/var/lib/docker/containers/ac2903c4e1676372b50909d512eee257a170a0aaa560c92b6a984bcd47d6ac0c/shm rw,nosuid,nodev,noexec,relatime - tmpfs shm rw,size=65536k
699 680 0:95 / /dev/shm rw,nosuid,nodev,noexec,relatime - tmpfs shm rw,size=65536k
```

The mount is created by Docker, so runc doesn't know how to dump it. Docker has to save a content of this mount and restore it before restoring the container.

@bhaktibohara could you file an issue to the Docker project?
@kolyshkin maybe you can help us with this issue;)

**Comment by kolyshkin** [comment] 2017-06-17 00:11
ok I was wrong; the above patch is not the reason why it's done that way, I'll keep digging

**Comment by kolyshkin** [comment] 2017-06-20 16:19
I think we can close this one as a duplicate for #300 to avoid confusion

**Comment by avagin** [comment] 2017-06-20 22:43
@kolyshkin Ok

**Closed by avagin** 2017-06-20 22:43 UTC
Labels: bug, bug-restore-fail
