### ISSUE TITLE
CRIU 2.4 regression with restoring unix sockets

### ISSUE THREAD

**Issue by tswift242** [xemul/criu#195] opened 2016-07-27 17:30 UTC
I have a Docker container which I am able to C/R successfully using CRIU v2.3. However, when I use the newly released CRIU v2.4, the restore fails with this error:

"Error (sk-unix.c:1216): sk unix: Can't make usk listen: Invalid argument"

The restore logs up to the point of the error look the same between 2.3 and 2.4, as does the entry in the unixsk image for the problematic socket. The socket that fails to be restored in 2.4 looks like this:

{
    "id": 1318,
    "ino": 483588,
    "type": 1,
    "state": 10,
    "flags": "0x2",
    "uflags": "0x0",
    "backlog": 5,
    "peer": 0,
    "fown": {
        "uid": 0,
        "euid": 0,
        "signum": 0,
        "pid_type": 0,
        "pid": 0
    },
    "opts": {
        "so_sndbuf": 212992,
        "so_rcvbuf": 212992,
        "so_snd_tmo_sec": 0,
        "so_snd_tmo_usec": 0,
        "so_rcv_tmo_sec": 0,
        "so_rcv_tmo_usec": 0,
        "reuseaddr": false,
        "so_priority": 0,
        "so_rcvlowat": 1,
        "so_mark": 0,
        "so_passcred": false,
        "so_passsec": false,
        "so_dontroute": false,
        "so_no_check": false
    },
    "name": ""
}

This is what I see in the restore log leading up to the failure (note that the restore logs contain some additional logging I added to help debug):

(00.917788)    928: Found fd 9 (id pipe:[474918]) in inherit fd list (caller inherit_fd_resolve_clash)
(00.917791)    928: Inherit fd 9 moved to 12 to resolve clash
(00.917798)    928: 		Create fd for 9
(00.917805)    928: 	Restoring fd 10 (state -> create)
(00.917810)    928: sk unix: Opening standalone socket (id 0x526 ino 0x76104 peer 0)
(00.917820)    928: sk unix: 	Putting 0x76104/483588 into listen state. Args: sockfd=10, backlog=5
Name=(null), name_dir=(null)
(00.917840)    928: Error (sk-unix.c:1221): sk unix: Can't make usk listen: Invalid argument

Doing a diff between the 2 unixsk images, the only difference I see is the presence of an extra socket in the 2.4 image which looks like this:

{
    "id": 2494, 
    "ino": 590475, 
    "type": 2, 
    "state": 10, 
    "flags": "0x0", 
    "uflags": "0x1", 
    "backlog": 0, 
    "peer": 0, 
    "fown": {
        "uid": 0, 
        "euid": 0, 
        "signum": 0, 
        "pid_type": 0, 
        "pid": 0
    }, 
    "opts": {
        "so_sndbuf": 0, 
        "so_rcvbuf": 0, 
        "so_snd_tmo_sec": 0, 
        "so_snd_tmo_usec": 0, 
        "so_rcv_tmo_sec": 0, 
        "so_rcv_tmo_usec": 0
    }, 
    "name": ""
}

A couple things that stick out about this socket are that the so_sndbuf and so_rcvbuf are 0 (all other unixsk's in the image are 212992), and the opts struct is missing some fields like reuseaddr and so_priority (again the only such unixsk). This is not the socket that causes the restore to fail, at least not directly. However, could this socket be indirectly leading to the failure? Since the arguments to the listen syscall are the same in both cases, it seems to be a state management issue.

I am using Linux kernel 4.4.13.

Any ideas what's going on here? Again, the only difference between a successful and failed restore for me is the CRIU version; everything else is the same.

**Comment by xemul** [comment] 2016-07-29 10:05
Hm...

The socket is created and immediately put into listen state, w/o binding. This is invalid, of course. I blame this commit: 3166032ecb406f0dd6e803c64e46413083736deb, but wonder how we get the unnamed listen socket. Can you show the dump.log file?

**Comment by xemul** [comment] 2016-07-29 10:07
Cc @tkhai

**Comment by tswift242** [comment] 2016-08-01 15:53
@xemul Thanks for looking into this. I can't provide the whole dump log, but I am providing all the parts of the log that relate to unix sockets (based on a grep for "unix"). That is attached. Is there anything else I can search for in the dump or restore logs that would be helpful?
[dump-2_4-unixsk.txt](https://github.com/xemul/criu/files/394216/dump-2_4-unixsk.txt)

**Comment by tkhai** [comment] 2016-08-01 20:27
Is it reproducible?

**Comment by tswift242** [comment] 2016-08-01 20:33
Yes, this happens for me every time on restore when using CRIU 2.4. I have never seen it when using CRIU 2.3.

**Comment by tkhai** [comment] 2016-08-01 20:37
So, could you provide dump log and corresponding restore log?

**Comment by xemul** [comment] 2016-08-02 11:07
@tswift242 , yes, if you cannot provide full logs and/or images, then at least this would be needed:

1. difference between unix sk image files when using 2.3 and 2.4
2. the decoded entry for the failed socket (both 2.3 and 2.4)
3. dump logs strings about unix for 2.3 and 2.4

I know you've already sent this, but we'll need to match identifiers to each other, so logs and images extractions from the same criu run would be required.

Can you do it?

**Comment by tswift242** [comment] 2016-08-02 15:31
Okay, I've provided the full dump and restore logs from the same CRIU 2.4 run. They're slightly censored, but all the log statements related to unixsk's should be intact. I'm also attaching the full, decoded unixsk images for both 2.3 and 2.4. I have the dump and restore logs from a CRIU 2.3 run as well. If those would be helpful, let me know and I can provide that as well. Thanks!
[dump-2_4.txt](https://github.com/xemul/criu/files/397379/dump-2_4.txt)
[restore-2_4.txt](https://github.com/xemul/criu/files/397382/restore-2_4.txt)
[unixsk-2_3.txt](https://github.com/xemul/criu/files/397381/unixsk-2_3.txt)
[unixsk-2_4.txt](https://github.com/xemul/criu/files/397380/unixsk-2_4.txt)

**Comment by tkhai** [comment] 2016-08-03 09:12
Dump:
(00.031560) sk unix: unix: Dropping path /tmp/.java_pid879.tmp for unlinked sk 0x3362f
(00.031563) sk unix: 	Collected: ino 0x3362f peer_ino 0 family    1 type    1 state 10 name (null)
(00.382541) sk unix: 	Dumping: ino 0x3362f peer_ino 0 family    1 type    1 state 10 name (null)
(00.382546) sk unix: 	Dumped: id 0x549 ino 0x3362f peer 0 type 1 state 10 name 0 bytes
Restore:
(00.163759)      1: sk unix:  `- Got 0x3362f peer 0 (name - dir -)
(00.918057)    879: sk unix: Opening standalone socket (id 0x549 ino 0x3362f peer 0)
(00.918073)    879: sk unix: 	Putting 0x3362f into listen state
(00.918093)    879: Error (sk-unix.c:1216): sk unix: Can't make usk listen: Invalid argument

**Comment by tkhai** [comment] 2016-08-03 09:46
Hm. Strange.

d->name is not zero in unix_process_name(), but in unix_collect_one->show_one_unix() it becomes NULL. Someone corrupts memory?!

**Comment by xemul** [comment] 2016-08-03 09:54
@tkhai , but the log message is explicit -- "Dropping path ... for unlinked sk".

**Comment by tkhai** [comment] 2016-08-03 10:41
It looks like, tswift242 doesn't have
commit 24da7e2c386d3e11d43915aa8bee8e2c96e8981e
Author: Tycho Andersen <tycho.andersen@canonical.com>
Date:   Tue Jul 5 15:15:07 2016 +0000

so, name is cleared in his case

**Comment by tkhai** [comment] 2016-08-03 10:43
Just for debug purpose, @tswift242, is the problem reproduces on latest criu-dev branch?

**Comment by xemul** [comment] 2016-08-03 11:18
@tkhai , but 2.3 didn't have this commit either, but it worked ;)

**Comment by tkhai** [comment] 2016-08-03 12:21
@xemul, in 2.3 it was autobinded to automatically generated name, I suppose

**Comment by xemul** [comment] 2016-08-03 13:23
@tkhai , OK, so AFAIU the problem is -- we have listening socket with name that is unlinked (for some reason). On 2.3 the name was dropped and the socket was auto-bound. In 2.4 the name was dropped, but the commit I mentioned avoided calling bind(). Right?

**Comment by tswift242** [comment] 2016-08-03 13:27
@tkhai I will try to reproduce using the criu-dev branch and let you know.

**Comment by tkhai** [comment] 2016-08-03 14:07
@xemul, right. Also, it seems Tycho has already fixed the problem in criu-dev branch.

**Comment by tswift242** [comment] 2016-08-03 14:12
@xemul @tkhai I get the following error trying to build CRIU from the criu-dev branch:

"In file included from /usr/include/signal.h:28:0,
                 from /usr/src/criu_latest/criu/arch/x86/include/asm/types.h:5,
                 from criu/arch/x86/syscalls/syscall32.c:1:
/usr/include/features.h:374:25: fatal error: sys/cdefs.h: No such file or directory
 #  include <sys/cdefs.h>"

Was a new build dependency introduced since 2.4?

**Comment by tkhai** [comment] 2016-08-03 14:18
I can't definitely say... But it seems in the same situation "make clean" helped me. Some leftover .deps file were there

**Comment by 0x7f454c46** [comment] 2016-08-03 14:23
@tswift242 hi, sorry about that -- please, check the new [Installation requiments](https://criu.org/Installation), I think, you'll need to install:
> glibc-devel.i686 (RPM) or libc6-dev-i386 (DEB) for building on x86-64
and if you have gcc, you may also need to install `gcc-multilib`
I promised and I'll make building without ia32 compiler support (by introducing CONFIG_COMPAT or something like that), as many step on this -- yet working on it.

**Comment by xemul** [comment] 2016-08-03 14:25
Guys, the needed patches are in current master branch :) Will be released with 2.5, but pulling one right now ... should work %) @0x7f454c46 , will it?

**Comment by 0x7f454c46** [comment] 2016-08-03 14:32
@xemul @tswift242 Yep, as compat-patches are outside in criu-dev, compiling master without multilib should be fine.

**Comment by tswift242** [comment] 2016-08-03 14:52
Just tested this with the master branch and the issue does indeed seem to be fixed. The restore worked. Thanks guys!

Something I'll open a separate issue about is I don't see this fixed on the master branch: "Mode was lost for PTY device file on restore" (that's from the 2.4 release changelog and I'm guessing corresponding to commit 8ba6372). In the container I just restored while verifying the unixsk fix, I have a pseudoterminal which is owned by root after restore but which was owned by an unprivileged user before checkpoint. Isn't that what 8ba6372 was supposed to address?

**Comment by xemul** [comment] 2016-08-03 14:54
@tswift242 , you're welcome :)

As far as the PTY issue is concerned -- yes, please, let's go to dedicated issue for this. Thanks :)

**Closed by xemul** 2016-08-03 14:54 UTC
Labels: bug

**Comment by cyrillos** [comment] 2016-08-03 16:24
fwiw, I've got same problem with socket on test on current master (ie after criu-2.4) But didn't look precise into the issue

**Comment by avagin** [comment] 2016-08-03 16:45
Why do our tests not detect this problem?

**Comment by cyrillos** [comment] 2016-08-03 16:57
I think my error is a side effect from vz commit
---
[root@nuncriu criu]# git bisect good
b4455c54cd641aec635bd274c88bacd3706f57ec is the first bad commit
commit b4455c54cd641aec635bd274c88bacd3706f57ec
Author: Cyrill Gorcunov <gorcunov@virtuozzo.com>
Date:   Sat Jun 4 14:12:27 2016 +0300

    sk-unix: Fix path resolving for sockets with abs symlinks in paths
    
    Signed-off-by: Cyrill Gorcunov <gorcunov@virtuozzo.com>
---
IOW, can't repeat it on master branch

**Comment by cyrillos** [comment] 2016-08-03 17:33
Actually, once I revert

commit 93eefc0d5acf3bcf1ce7ac425f8c01eb89c239e0
Author: Cyrill Gorcunov <gorcunov@openvz.org>
Date:   Wed Aug 3 20:32:03 2016 +0300

    Revert "unix: Do not autobind unnamed unix sockets"
    
    This reverts commit 3166032ecb406f0dd6e803c64e46413083736deb.

The test start working back.

**Comment by cyrillos** [comment] 2016-08-03 17:33
there is something wrong with autobinding

**Comment by cyrillos** [comment] 2016-08-03 17:33
will make a close look tomorrow

**Comment by cyrillos** [comment] 2016-08-03 19:39
ah, it looks like I need a patch from Tycho 24da7e2c386d3e11d43915aa8bee8e2c96e8981e
