### ISSUE TITLE
Cgroups are not restored when using C/R on Docker container.

### ISSUE THREAD

**Issue by tswift242** [xemul/criu#305] opened 2017-04-03 14:52 UTC
After restoring a Docker container, it seems that none of the cgroups were restored. I've found that I can use as much memory or pids as I want, despite specifying limits for those. ```docker inspect``` shows the cgroups limits that I've specified, but they don't seem to actually be enforced. ```docker stats``` does not show any limit (e.g. for memory), which appears to be the truth. Simple reproduction steps:

1) docker run --pids-limit=10 --name cr -d --rm ubuntu:14.04 /bin/bash -c 'sleep 10 && for i in $(seq 1 1000); do sleep 10 & done && sleep 1000000'
2) docker checkpoint create --checkpoint-dir /var/lib/docker/checkpoints cr test_cp
3) docker create --pids-limit=10 --name cr1 --rm ubuntu:14.04 && docker start --checkpoint-dir /var/lib/docker/checkpoints --checkpoint test_cp cr1
4) docker stats cr1
5) Wait 10 seconds.
6) Observe pids spikes over 1000 despite me setting a limit of 10.

You can also do a similarly simple example but with exceeding memory cgroup limits . Note that I'm specifying cgroups limits on both the checkpointed container and the restored container, but this doesn't seem to help.

I'm using Docker 17.03.0-ce, criu 2.11, and kernel 4.10.5.

cc @xemul @boucher

**Comment by boucher** [comment] 2017-04-03 14:56
Does the error reproduce if you don't create a new container?

**Comment by tswift242** [comment] 2017-04-03 15:00
Just tried. Yes, I see the same behavior even when I don't create a new container.

1) docker run --pids-limit=10 --name cr -d ubuntu:14.04 /bin/bash -c 'sleep 10 && for i in $(seq 1 1000); do sleep 10 & done && sleep 1000000'
2) docker checkpoint create --checkpoint-dir /var/lib/docker/checkpoints cr test_cp
3) docker start --checkpoint-dir /var/lib/docker/checkpoints --checkpoint test_cp cr

**Comment by xemul** [comment] 2017-04-03 16:20
Cc @avagin

**Comment by tswift242** [comment] 2017-04-06 13:38
@xemul @avagin Can someone please take a look at this? Not sure if this a criu bug or a docker/containerd/runc bug, but it'd be great to triage and start investigating this. This seems like a pretty critical issue which needs fixing. It's blocking our adoption of C/R, and I would think it would concern other users of the Docker C/R integration as well.

**Comment by avagin** [comment] 2017-04-06 22:59
Looks like it was broken in the next commit
commit 8a740d5391a7523a26ddb886a823cadcbf70ac6d
Author: @cyphar
Date:   Thu Dec 17 19:20:58 2015 +1100

    libcontainer: cgroups: don't Set in Apply

**Comment by tswift242** [comment] 2017-04-07 13:32
@avagin Thanks for looking at this! Is it worth creating an issue for this to runc or docker instead of tracking it here?

**Comment by avagin** [comment] 2017-04-14 00:03
https://github.com/opencontainers/runc/commit/57ef30a2ae432115f04678bc905b59451bddb5b8

@tswift242 Thank you for the report. My fix has been committed into runc. Can we close this issue?

**Comment by tswift242** [comment] 2017-04-14 03:40
@avagin Thanks so much for working on this! Yes you can close this issue. However the docker issue linked to this one should remain open until the runc fix is integrated into docker. Can you please help get the runc fix into docker?

**Comment by xemul** [comment] 2017-04-20 12:38
Thanks, closing.

**Closed by xemul** 2017-04-20 12:38 UTC
Labels: bug, docker
