### ISSUE TITLE
criu dump hangs up

### ISSUE THREAD

**Issue by avagin** [xemul/criu#162] opened 2016-05-20 17:28 UTC
```
[root@usr-LAN-dhcp-38 criu]# ps axf
  PID TTY      STAT   TIME COMMAND
  103 pts/3    S      0:00 -bash
  204 pts/3    R+     0:00  \_ ps axf
    1 ?        S      0:00 python2 zdtm.py
    3 ?        S      0:00 python2 zdtm.py
   60 ?        S      0:00  \_ ../criu/criu dump -o dump.log -D dump/zdtm/static/fd/54/1 -v4 -t 54 --pidfile /var/lib/jenkins/workspace/CRIU/CRIU-restore-sibl
   54 ?        Ss     0:00 ./fd --pidfile=fd.pid --outfile=fd.out
   57 ?        ts     0:00  \_ ./fd --pidfile=fd.pid --outfile=fd.out
   58 ?        t      0:00      \_ ./fd --pidfile=fd.pid --outfile=fd.out
```

```
(00.053770) cg: Dumping cgroups for 54
(00.054077) cg:  `- Existing css 1 found
(00.054101) cg: Set 1 is root one
(00.054296) ----------------------------------------
(00.054348) Waiting for 54 to trap
(00.054484) Daemon 54 exited trapping
(00.054516) Sent msg to daemon 6 0 0
pie: __fetched msg: 6 0 0
pie: 1: new_sp=0x7f2b9fc64008 ip 0x7f2b9f7887a7
```

**Comment by avagin** [comment] 2016-05-20 17:28
```
(gdb) bt
#0  0x00007fbd3532918a in wait4 () from target:/lib64/libc.so.6
#1  0x00000000004600f6 in parasite_stop_on_syscall (tasks=tasks@entry=1, sys_nr=sys_nr@entry=15, trace=TRACE_EXIT) at parasite-syscall.c:954
#2  0x0000000000460e4a in parasite_fini_seized (ctl=ctl@entry=0x1c40840) at parasite-syscall.c:922
#3  0x0000000000461029 in parasite_stop_daemon (ctl=ctl@entry=0x1c40840) at parasite-syscall.c:1029
#4  0x00000000004357ea in dump_one_task (item=0x1c3a050) at cr-dump.c:1348
#5  cr_dump_tasks (pid=pid@entry=54) at cr-dump.c:1712
#6  0x000000000041f011 in main (argc=<optimized out>, argv=0x7ffc054dd708, envp=<optimized out>) at crtools.c:724
```

**Comment by avagin** [comment] 2016-05-20 17:33
```
                ret = ptrace_set_breakpoint(pid, addr);
        if (ret < 0)
                return ret;
             
        if (ret > 0) {
                /*
                 * PIE will stop on a breakpoint, next
                 * stop after that will be syscall enter.
                 */
                *tf = TRACE_EXIT;
                return 0;
        }

```

**Comment by avagin** [comment] 2016-05-20 17:34
Looks like the 30883 process has not stopped on a breakpoint.

**Comment by avagin** [comment] 2016-05-20 17:56
```
[root@usr-LAN-dhcp-38 criu]# cat test/54/syscall 
202 0x6063e0 0x0 0x0 0x0 0x0 0x0 0x7ffc15e63c48 0x7f2b9f7887a9
[root@usr-LAN-dhcp-38 criu]# cat test/54/sta
stack   stat    statm   status  
[root@usr-LAN-dhcp-38 criu]# cat test/54/sta
stack   stat    statm   status  
[root@usr-LAN-dhcp-38 criu]# cat test/54/stack 
[<ffffffff81120fec>] futex_wait_queue_me+0xbc/0x120
[<ffffffff81121386>] futex_wait+0x116/0x270
[<ffffffff8112334b>] do_futex+0x12b/0xb20
[<ffffffff81123dc1>] SyS_futex+0x81/0x180
[<ffffffff817a0f2e>] entry_SYSCALL_64_fastpath+0x12/0x71
[<ffffffffffffffff>] 0xffffffffffffffff
```

**Comment by avagin** [comment] 2016-05-20 18:06
```
[root@usr-LAN-dhcp-38 criu]# cat /proc/30883/map_files/7f2b9fc5b000-7f2b9fc69000  > log
[root@usr-LAN-dhcp-38 criu]# 
[root@usr-LAN-dhcp-38 criu]# objdump -D -b binary -mi386 log | head -n 50

log:     file format binary  


Disassembly of section .data:

00000000 <.data>:
       0:       48                      dec    %eax
       1:       83 ec 10                sub    $0x10,%esp
       4:       48                      dec    %eax
       5:       83 e4 f0                and    $0xfffffff0,%esp
       8:       6a 00                   push   $0x0
       a:       48                      dec    %eax
       b:       89 e5                   mov    %esp,%ebp
       d:       8b 3d 0d 00 00 00       mov    0xd,%edi
      13:       48                      dec    %eax
      14:       8d 35 92 3c 00 00       lea    0x3c92,%esi
      1a:       e8 81 12 00 00          call   0x12a0
      1f:       cc                      int3   
      20:       02 00                   add    (%eax),%al
      22:       00 00                   add    %al,(%eax)
      24:       66 2e 0f 1f 84 00 00    nopw   %cs:0x0(%eax,%eax,1)
      2b:       00 00 00 
      2e:       66 90                   xchg   %ax,%ax
      30:       48                      dec    %eax
      31:       89 f8                   mov    %edi,%eax
      33:       48                      dec    %eax
      34:       89 c4                   mov    %eax,%esp
      36:       b8 0f 00 00 00          mov    $0xf,%eax
      3b:       0f 05                   syscall 
```

**Comment by avagin** [comment] 2016-05-20 18:07
```
(gdb) p ctl->sigreturn_addr 
$1 = (void *) 0x7f2b9fc5b030
```

**Comment by avagin** [comment] 2016-05-20 18:11
```
[root@usr-LAN-dhcp-38 criu]# kill -STOP 30713 30640 30635
[root@usr-LAN-dhcp-38 criu]# kill -9 30896
[root@usr-LAN-dhcp-38 criu]# gdb -p 30883 /var/lib/jenkins/workspace/CRIU/CRIU-restore-sibling/criu-dev/test/zdtm/static/fd

(gdb) bt
#0  0x00007f2b9f7887a9 in syscall () from target:/lib64/libc.so.6
#1  0x0000000000402973 in sys_futex (val3=0, uaddr2=0x0, timeout=0x0, val=0, op=0, uaddr=0x6063e0 <sig_received>) at lock.h:29
#2  futex_wait_while (f=0x6063e0 <sig_received>, v=0) at lock.h:121
#3  test_waitsig () at test.c:262
#4  0x00000000004032ff in ns_init (argc=argc@entry=3, argv=argv@entry=0x7ffc15ea4f88) at ns.c:319
#5  0x000000000040247c in test_init (argc=3, argv=0x7ffc15ea4f88) at test.c:135
#6  0x0000000000401a60 in main (argc=<optimized out>, argv=<optimized out>) at fd.c:25
(gdb)
```

**Comment by avagin** [comment] 2016-05-20 18:30
```
[root@usr-LAN-dhcp-38 criu]# cat ptrace.c
#include <sys/ptrace.h>
#include <stdio.h>
#include <sys/wait.h>
#include <sys/user.h>
#include <string.h>
#include <stdlib.h>

#define DR_FIRSTADDR 0
#define DR_LASTADDR  3
#define DR_NADDR     4  /* The number of debug address registers.  */
#define DR_STATUS    6  /* Index of debug status register (DR6).  */
#define DR_CONTROL   7  /* Index of debug control register (DR7).  */

# define offsetof(TYPE, MEMBER) ((size_t) &((TYPE *)0)->MEMBER)
int main(int argc, char *argv[])
{
        pid_t pid = atoi(argv[1]);
        unsigned long addr;

        if (ptrace(PTRACE_ATTACH, pid, 0, 0))
                return 1;
        waitpid(pid, NULL, 0);

        addr = ptrace(PTRACE_PEEKUSER, pid,
                        offsetof(struct user, u_debugreg[DR_CONTROL]),
                       NULL);
        printf("%lx\n", addr);
        addr = ptrace(PTRACE_PEEKUSER, pid,
                        offsetof(struct user, u_debugreg[DR_FIRSTADDR]),
                       NULL);
        printf("%lx\n", addr);
        addr = ptrace(PTRACE_PEEKUSER, pid,
                        offsetof(struct user, u_debugreg[DR_STATUS]),
                       NULL);
        printf("%lx\n", addr);


        return 0;
}
[root@usr-LAN-dhcp-38 criu]# ./a.out 30883
1
7f2b9fc5b030
0
```

**Comment by avagin** [comment] 2016-05-20 18:32
We can set that a breakpoint is set correctly and it has not been triggered (DR_STATUS = 0)

**Comment by avagin** [comment] 2016-05-20 20:30
@0x7f454c46 @cyrillos , could you take a look at this issue?

**Comment by cyrillos** [comment] 2016-05-20 20:46
will do, thanks

**Comment by 0x7f454c46** [comment] 2016-05-20 21:36
Sure.

**Comment by avagin** [comment] 2016-05-23 06:35
Here is a reproducer. It should be executed a few times concurrently. 
https://gist.github.com/avagin/3c9e2d30b7ffac6dbc31e7f1bb2b61f8

**Comment by 0x7f454c46** [comment] 2016-05-23 11:58
Does it depend on hw/kernel vers?
```
[ptrace-test]$ uname -a
Linux dsafonov 4.5.4-1-ARCH #1 SMP PREEMPT Wed May 11 22:21:28 CEST 2016 x86_64 GNU/Linux
[ptrace-test]$ cat /proc/cpuinfo | grep 'model name'
model name	: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
...
[ptrace-test]$ jobs -l
[1]  13370 Running                 ./bp2 &
[2]  30709 Running                 ./bp2 &
[3]  10563 Running                 ./bp2 &
[4]  31165 Running                 ./bp2 &
[5]   4203 Running                 ./bp2 &
[6]   4872 Running                 ./bp2 &
[7]  30622 Running                 ./bp2 &
[8]  21716 Running                 ./bp2 &
[9]  12369 Running                 ./bp2 &
[10]  23915 Running                 ./bp2 &
[11]  26249 Running                 ./bp2 &
[12]  16376 Running                 ./bp2 &
[13]   2879 Running                 ./bp2 &
[14]- 22125 Running                 ./bp2 &
[15]+ 15914 Running                 ./bp2 &
[ptrace-test]$ for i in $(jobs -p) ; do ps -p $i -o etimes= ; done
    840
    838
    838
    837
    800
    800
    799
    798
    349
    348
    347
    347
    346
    346
    344
```

**Comment by cyrillos** [comment] 2016-05-23 12:05
Same here, ran them on two machines and it didn't trigger.

**Comment by avagin** [comment] 2016-05-23 14:52
https://asciinema.org/a/34n50nn9hirtld5lnzmgt5svl

I reproduced this bug on my laptop and on the fitlet (amd64).  You need to wait a few minutes.

**Comment by cyrillos** [comment] 2016-05-23 17:04
While it passed on 3.10 kernel series, on my laptop with 4.4.9-300.fc23.x86_64 it triggered. It took ~ 5 min to trigger.

**Comment by avagin** [comment] 2016-05-23 17:12
@xemul You can add the kernel label. The problem isn't in criu. I think we need to disable logic about breakpoints in criu, before it will not be fixed in kernel and backported in stable kernels.

**Comment by avagin** [comment] 2016-05-25 16:10
http://www.gossamer-threads.com/lists/linux/kernel/2444358

**Comment by avagin** [comment] 2016-05-25 16:11
This bug was fixed in the v4.5 kernel.

**Comment by xemul** [comment] 2016-05-25 16:55
Should we handle this in criu sources somehow? We're kinda supporting 3.11.

**Comment by avagin** [comment] 2016-05-25 17:13
We don't know where it was broken and where is was fixed exactly. I have an reproducer and I tried to bisect a commit twice without success.

I know that rhel7 doesn't have this bug. I recommend to check Ubuntu LTS kernels and forget about this bug.

Cc: @tych0

**Comment by 0x7f454c46** [comment] 2016-05-25 17:28
Hmm, how can we for sure know that the problem is gone?
I mean, it may happen more rarely because of some other patch's side-effect.
I don't mean anything, it's not CRIU bug anyway, just my 5 cents.

**Comment by avagin** [comment] 2016-05-25 17:45
@0x7f454c46 5 cents isn't enough;). Can you take my reproducer and try to bisect a commit which fixed this problem. I know that the bug exists in v4.4 and was fixed in v4.5. I think if we found the commit where it was fixed, we will be able to understand where it appeared.

**Comment by 0x7f454c46** [comment] 2016-05-25 18:06
@avagin and we could tag it stable then. Yep, I'll try to help you with this.

**Comment by tych0** [comment] 2016-05-25 19:14
On Wed, May 25, 2016 at 10:21:04AM -0700, Andrew Vagin wrote:
> We don't know where it was broken and where is was fixed exactly. I have an reproducer and I tried to bisect a commit twice without success.
> 
> I know that rhel7 doesn't have this bug. I recommend to check Ubuntu LTS kernels and forget about this bug.

Ubuntu 16.04 is the only distro we support CRIU on, and it's got a 4.4
kernel :(

If we identify a kernel commit that fixes this and it's not too
invasive, I can have it backported to the 16.04 kernel.

**Comment by xemul** [comment] 2016-09-02 14:12
Gents, what are the plans about it?

**Comment by cyrillos** [comment] 2016-09-02 14:31
I think the only way is to wait until fix get merged into stable kernel.

**Comment by xemul** [comment] 2016-10-20 11:28
OK, so do we want to keep this issue open as a reminder for us to look for the fix? Or just forget about it and wait for the fix to flow into the modern kernels by itself :)

**Comment by cyrillos** [comment] 2016-10-20 12:00
The second, I think. Even if opened we can't do much about it, the kernel needs fixing.

**Closed** 2016-10-21 12:12 UTC
Labels: bug, dangling, kernel
