### ISSUE TITLE
CRIU dump fails with network error

### ISSUE THREAD

**Issue by upuvvad1** [xemul/criu#237] opened 2016-10-26 18:57 UTC
lamp stack on the lxc container, with heavy incoming HTTP connections, the live migration fails with

(04.604753)     Searching for socket 22734 (family 10.6)
(04.604758) Error (criu/sk-inet.c:202): Name resolved on unconnected socket
(04.604762) ----------------------------------------
(04.604776) Error (criu/cr-dump.c:1312): Dump files (pid: 15347) failed with -1
(04.604805) Waiting for 15347 to trap

However, when the container was idle, the migration will succeed.

**Comment by xemul** [comment] 2016-10-26 19:34
Cc @avagin

**Comment by tswift242** [comment] 2016-10-26 21:37
I've also gotten that "Name resolved on unconnected socket" error in a couple different ways while working with Docker's C/R integration. What is usually the cause of that error? I currently am getting that error sporadically (maybe ~1/3 of the time) when I try to checkpoint my application.

**Comment by upuvvad1** [comment] 2016-10-26 21:47
I think this happens when client has requested for a page, and then if migration/snapshot was triggered, the CRIU locks up the network and dumps all the processes, in the processes of this if the client terminates the request (before CRIU dumps the socket information), the client-side socket was closed and the CRIU wasn't unable to resolve the socket.
Since the network was locked, CRIU doesn't update the internal socket list what it needs to dump I guess.

**Comment by avagin** [comment] 2016-11-01 21:01
Now CRIU doesn't support transit states of TCP sockets and it is impossible to support them without patching the kernel.

We have a draft set to support closing states:
https://github.com/avagin/linux-task-diag/tree/tcp-v3
https://github.com/avagin/criu/tree/tcp-closing-states

And CRIU has the --skip-in-flight option to skip in-flight connections.

Cc: @cyrillos 

Here is a very similar issue: https://github.com/xemul/criu/issues/194

**Comment by cyrillos** [comment] 2016-11-01 21:04
Aha! Thank you a lot! I'll take a look once time permit.

**Comment by xemul** [comment] 2017-01-16 09:07
2.10 has transitional states support.

**Closed by xemul** 2017-01-16 09:07 UTC
Labels: bug, bug-tcp
