### ISSUE TITLE
10:14:04.907:    31: FAIL: cgroup03.c:105: mode for cgroup03.test/zdtmtst/test doesn't match (40600)

### ISSUE THREAD

**Issue by avagin** [xemul/criu#258] opened 2016-12-08 07:15 UTC
````
[root@fc24 criu]# python test/zdtm.py run -T zdtm/static/cgroup -p4 -x stray
....
======================== Run zdtm/static/cgroup03 in h =========================
Start test
Test is SUID
./cgroup03 --pidfile=cgroup03.pid --outfile=cgroup03.out --dirname=cgroup03.test
Cleaning cgclean.PjOcIs
Cleaning cgclean.ZTyxcw
Running zdtm/static/cgroup03.hook(--post-start)
Running zdtm/static/cgroup03.hook(--pre-dump)
Run criu dump
Running zdtm/static/cgroup03.hook(--pre-restore)
Run criu restore
Running zdtm/static/cgroup03.hook(--post-restore)
Send the 15 signal to  31
Wait for zdtm/static/cgroup03(31) to die for 0.100000
################ Test zdtm/static/cgroup03 FAIL at result check ################
Test output: ================================
10:14:04.907:    31: FAIL: cgroup03.c:105: mode for cgroup03.test/zdtmtst/test doesn't match (40600)
 (errno = 11 (Resource temporarily unavailable))

 <<< ================================
Running zdtm/static/cgroup03.hook(--clean)
```

@tych0 Could you take a look at this issue

**Comment by tych0** [comment] 2016-12-08 08:04
Yes, I think this is a dupe of #253

**Closed** 2016-12-08 14:12 UTC
