### ISSUE TITLE
[Docker] Checkpoint fails when the process has a lot of file descriptors

### ISSUE THREAD

**Issue by andreituicu** [xemul/criu#145] opened 2016-03-31 12:59 UTC
I am having problems checkpointing an application that has a lot of open file descriptors. At some point in the transfer of the FDs, the received message is truncated and the checkpointing fails here:
https://github.com/xemul/criu/blob/master/criu/pie/util-fd.c#L145

I have added some debugging messages in the criu code like so: https://gist.github.com/andreituicu/eac01d315ec97785ab82bc3dfb586097#file-util-fd-c-recv_fds
and the resulting dump log shows that the length of the message received is not the one that it was expected:
https://gist.github.com/andreituicu/eac01d315ec97785ab82bc3dfb586097#file-dump-log

```
Criu version: 2.0 GitID: v2.0-81-g89ba548 (which is  version: 2.0 GitID: v2.0-44-gef4dbeb + @avagin's commit  89ba548)
Docker version: 1.10.0-dev, build cec56b2, experimental
Kernel version: 4.4.0-10-generic
```

I think it might be related to what this commit in the kernel is trying to address http://lkml.iu.edu/hypermail/linux/kernel/1601.2/02786.html , but I haven't been able to get a consistent fail on odd, success on even. It might be just a part of the problem, or not related at all.

I have created and uploaded a VirtualBox machine with a docker container that has a dummy application that opens a lot of fds here: https://drive.google.com/file/d/0Bz4oADNI4d8-eHFNUTZXdEIweGc/view?usp=sharing . 
Username: andrei Password: password

Steps to reproduce:
In terminal 1:
`sudo docker daemon`

In termnal 2:
```
sudo docker run -d --name fds fds-env
sudo docker checkpoint fds
```

The application's source code can be found in /home/andrei/fds-env/lots-of-fds.c . If you need to modify it, just run make afterwards and the Makefile will recreate the docker image needed for running the container.

I have investigated this problem quite a bit, because I wanted to make the patch for solving it myself, but I was unable to find a fix, or a workaround. Could you please help me with this issue? 

Please let me know if you need any more information.

Thank you very much,
Andrei

**Comment by xemul** [comment] 2016-03-31 17:15
This can be (I actually believe it is) due to we try to send ALL the descriptors form parasite to criu for dump. The proper fix would be to drain descriptors in smaller chunks, that fit the kernel limits.

The code to look into for this is criu/pie/parasite.c drain_fds() and criu/files.c dump_task_files_seized(). The latter should run its body in a loop draining fds in chunks.

**Comment by andreituicu** [comment] 2016-03-31 17:33
Hi @xemul,

I hope I understand correctly what you are saying, I'm not very familiar with the codebase, so please correct me if I'm wrong.
I've looked into criu/pie/parasite.c, into the drain_fds() function. There the send_fds function from criu/pie/util-fd.c is called and although it receives all the FDs for a particular pid, it sends them in multiple messages, using a loop[[0]](https://github.com/xemul/criu/blob/master/criu/pie/util-fd.c#L68) that fit the kernel limits. It sends at most 252[[1]](https://github.com/xemul/criu/blob/master/criu/include/util-pie.h#L24) FDs at the time and the kernel supports 253[[2]](http://lxr.free-electrons.com/source/include/net/scm.h?v=4.4#L13).

Unfortunately, I think the problem is more complex than just too many FDs being sent at one time. This was my initial guess too, the second one was that the lengths fields of the message were not properly set.

Again, please correct me if I'm wrong. :)

Thank you,
Andrei

[0] https://github.com/xemul/criu/blob/master/criu/pie/util-fd.c#L68
[1] https://github.com/xemul/criu/blob/master/criu/include/util-pie.h#L24
[2] http://lxr.free-electrons.com/source/include/net/scm.h?v=4.4#L13

**Comment by avagin** [comment] 2016-03-31 17:38
@andreituicu you can try this patch, but I'm not sure that it fixes anything.
```
@@ -25,10 +25,10 @@ static void scm_fdset_init_chunk(struct scm_fdset *fdset, int nr_fds)
 {
        struct cmsghdr *cmsg;
 
-       fdset->hdr.msg_controllen = CMSG_LEN(sizeof(int) * nr_fds);
+       fdset->hdr.msg_controllen = CMSG_SPACE(sizeof(int) * nr_fds);
 
        cmsg            = CMSG_FIRSTHDR(&fdset->hdr);
-       cmsg->cmsg_len  = fdset->hdr.msg_controllen;
+       cmsg->cmsg_len  = CMSG_LEN(sizeof(int) * nr_fds);
 }
```

**Comment by xemul** [comment] 2016-03-31 17:45
@andreituicu , yes, you're correct that fds are sent in 252 buckets, but there are two more things:
1. total sum of the in-kernel socket buffers cannot exceed a certain limit
2. the fd table of criu itself cannot exceed another limit
neither of these two limits are taken into account by this code.

However, it's also possible that the lengths of the existing messages and cmsgs are also set with errors.

**Comment by andreituicu** [comment] 2016-03-31 18:00
@avagin:
 Thank you, although it seems like that is the proper way to set those lengths, I still get the error. :(

@xemul : 
1. This could be the actual problem, because I see the parasite sending all the fdsets even though criu doesn't call recv for all of them. I don't know exactly how the internals of sendmsg work. I think it is a blocking call, but I don't know if it blocks until recvmsg is called, or just until the data is copied into the kernel buffer.
I thought that maybe and ack for each bucket sent would solve this problem, but this exceeded a bit my coding skills. :) 

2. I think the I am in the limit of fds accepted by criu, which I belive is this one[[0]](https://github.com/xemul/criu/blob/master/criu/include/parasite.h#L224). Even the dummy app that is in the VM has just 1003 (1004) fds. And I think that macro on x86_64 expands to 1024.

[0] https://github.com/xemul/criu/blob/master/criu/include/parasite.h#L224

**Comment by avagin** [comment] 2016-03-31 18:03
@andreituicu can you try to increase ulimit for files before staring criu?
```
ulimit -n unlimited
```

**Comment by andreituicu** [comment] 2016-03-31 18:05
@avagin  I get Operation not permited.

`bash: ulimit: open files: cannot modify limit: Operation not permitted`

**Comment by avagin** [comment] 2016-03-31 18:07
@andreituicu try to set a big value ;)
```
ulimit -n 102400
```

**Comment by avagin** [comment] 2016-03-31 18:07
Actually, I've reproduced your problem and ulimit helps me

**Comment by andreituicu** [comment] 2016-03-31 18:10
@avagin I still get it... It is true that sometimes it doesn't happen for me either. I got this a lot when I was modifying the code. It seemed to be working, but then I would change the number of fds and it would happen again.

**Comment by avagin** [comment] 2016-03-31 18:15
@andreituicu How do you set ulimit? You need to call ulimit -n 102400 and then execute a docker daemon. Both commands should be executed from one session (w/o sudo).

**Comment by avagin** [comment] 2016-03-31 18:21
@andreituicu, can you try out this patch?

```
--- a/criu/cr-dump.c
+++ b/criu/cr-dump.c
@@ -1618,6 +1618,10 @@ int cr_dump_tasks(pid_t pid)
        int pre_dump_ret = 0;
        int ret = -1;
 
+       pr_err("xxx\n");
+       struct rlimit rlim = {1024000, 1024000};
+       setrlimit(RLIMIT_NOFILE, &rlim);
+
        pr_info("========================================\n");
        pr_info("Dumping processes (pid: %d)\n", pid);
        pr_info("========================================\n");
```

**Comment by andreituicu** [comment] 2016-03-31 18:38
@avagin : Wow, , you are a wizard. :) I've been staring for 3 days into the code, checking all the lengths and the sizes of the buffers and comparing them to the kernel ones, but I did not once think of increasing the ulimit for fds. This was a bit embarrassing... :) The second time was running ulimit in a different session. Thank you very much! I'll apply the patch and see if it works without the bash command, but I have no doubt it will.

@xemul @avagin Thank you guys for the help! I'm sorry for the noise... Lesson learned, ask first. :)

**Comment by andreituicu** [comment] 2016-03-31 18:58
@avagin Just tried the patch, it works as expected, just that it needs to be added in cr-restore.c too. Will this patch be in criu, or do I need to set the limit from the command line before running docker?

**Comment by xemul** [comment] 2016-04-06 12:01
Fixed in criu-dev. Will likely be in 2.1

**Closed by xemul** 2016-04-06 12:01 UTC
Labels: bug

**Comment by andreituicu** [comment] 2016-04-06 12:09
Thanks again! :)
