### ISSUE TITLE
Docker Checkpointing of Meteor App fails

### ISSUE THREAD

**Issue by b-studios** [xemul/criu#71] opened 2015-10-06 12:30 UTC
I try to checkpoint a docker container running a meteor sample application. The dockerfile can be found in [this gist](https://gist.github.com/b-studios/87985b7afd5225c2c4bf).

After building, I run the container with
~~~
docker run -d --name meteor meteor
~~~

Trying to checkpoint it with
~~~
docker checkpoint --image-dir=/tmp/meteor meteor
~~~
results in a failed dump, see the [dump.log](https://gist.github.com/b-studios/c4cb6ebd51111eda877e).

I am running Ubuntu 15.04 with
~~~
$ criu --version
Version: 1.7

$ docker -v
Docker version 1.9.0-dev, build 5dda3d1, experimental
~~~

Docker is build from sources using the @boucher's [cr-combined branch](https://github.com/boucher/docker/tree/cr-combined). Criu is installed from the repositories.

I think the interesting lines in the dump are
~~~
(00.176632) Error (proc_parse.c:1626): No records of type 0 found in fdinfo file
(00.176638) Error (proc_parse.c:1629): parse_fdinfo_pid_s: error parsing [(null)] for 0: Resource temporarily unavailable
(00.176642) Error (files.c:394): Can't get stat on 17: Resource temporarily unavailable
(00.176695) ----------------------------------------
(00.176709) Error (cr-dump.c:1255): Dump files (pid: 2429) failed with -1
~~~

but I can only find [this mail](https://lists.openvz.org/pipermail/criu/2015-May/020481.html) from the mailinglist.

Is there a somewhat stable combination of criu / docker versions that supports checkpointing containers with networking?

Thanks in advance

**Comment by b-studios** [comment] 2015-10-06 12:36
Just figured that this might be a duplicate of #62.

**Comment by boucher** [comment] 2015-10-06 16:30
I'm not sure it's a duplicate; when I have seen that problem it produced a
different error in the logs.

**Comment by boucher** [comment] 2015-10-06 16:31
Jonathan, have you built my branch recently, or did you use the precompiled
release? If you have a chance, could you try whichever you haven't?

I just rebased my branch a few days ago and I believe there is at least one
issue I haven't tracked down yet that I'm hoping to get to today.

**Comment by b-studios** [comment] 2015-10-06 16:33
I rebuild your branch just shortly before reporting this bug. With using a precompiled release you mean I should use the Docker experimental build?

**Comment by boucher** [comment] 2015-10-06 16:38
No, there's a precompiled docker binary on this page I'd like you to try:
https://github.com/boucher/docker/releases/tag/v1.9.0-experimental-cr.1

**Comment by b-studios** [comment] 2015-10-06 17:31
Thanks, I somehow missed this prebuilt version. However, after replacing docker and criu with the prebuilt ones I get a [different dump](https://gist.github.com/b-studios/3ca642f11fa7508ed1c2).

The error
~~~
Error (file-lock.c:225): Some file locks are hold by dumping tasks!You can try --file-locks to dump them.
~~~
confuses me, since the patched version of criu should have this option enabled.

~~~
$ criu --version
Version: 1.6
GitID: v1.6-5-g5e1a8a2
~~~

**Comment by boucher** [comment] 2015-10-06 17:37
Hmm. That's unfortunate. I'll be looking into some things in the current branch today, if I get any idea what might be going wrong I'l update this thead.

**Comment by xemul** [comment] 2016-10-20 11:21
OK, so this is more than one year old already :) Let's close it and if the problem is still there (likely it's not) -- re-open.

**Closed by xemul** 2016-10-20 11:21 UTC
Labels: docker
